-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity QuantizationDithering_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img0_data_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img0_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img0_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img0_data_empty_n : IN STD_LOGIC;
    img0_data_read : OUT STD_LOGIC;
    img1_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    img1_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img1_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img1_data_full_n : IN STD_LOGIC;
    img1_data_write : OUT STD_LOGIC;
    mul_ln177 : IN STD_LOGIC_VECTOR (20 downto 0);
    offset_buffer_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_2_ce0 : OUT STD_LOGIC;
    offset_buffer_2_we0 : OUT STD_LOGIC;
    offset_buffer_2_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    offset_buffer_2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_2_ce1 : OUT STD_LOGIC;
    offset_buffer_2_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    offset_buffer_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_1_ce0 : OUT STD_LOGIC;
    offset_buffer_1_we0 : OUT STD_LOGIC;
    offset_buffer_1_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    offset_buffer_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_1_ce1 : OUT STD_LOGIC;
    offset_buffer_1_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    width : IN STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_ce0 : OUT STD_LOGIC;
    offset_buffer_we0 : OUT STD_LOGIC;
    offset_buffer_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    offset_buffer_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    offset_buffer_ce1 : OUT STD_LOGIC;
    offset_buffer_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    add_ln177 : IN STD_LOGIC_VECTOR (11 downto 0);
    zext_ln109 : IN STD_LOGIC_VECTOR (10 downto 0) );
end;


architecture behav of QuantizationDithering_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_3F : STD_LOGIC_VECTOR (7 downto 0) := "00111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln177_reg_1499 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln191_reg_1508 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op64_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal icmp_ln191_reg_1508_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln177_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal img1_data_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal img0_data_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln109_cast_fu_293_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln109_cast_reg_1494 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln191_fu_374_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln191_reg_1503 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln191_reg_1503_pp0_iter2_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln191_reg_1503_pp0_iter3_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln191_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln191_reg_1508_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp221_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp221_reg_1512 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp221_reg_1512_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp221_reg_1512_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_fu_389_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_reg_1516 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_reg_1516_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp239_reg_1516_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal offset_buffer_load_reg_1549 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln213_2_fu_410_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln213_2_reg_1554 : STD_LOGIC_VECTOR (1 downto 0);
    signal offset_buffer_1_load_reg_1559 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln213_5_fu_414_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln213_5_reg_1564 : STD_LOGIC_VECTOR (1 downto 0);
    signal offset_buffer_2_load_reg_1569 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln213_8_fu_418_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln213_8_reg_1574 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_load82_reg_1579 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i5868_load_reg_1584 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp1_reg_1590 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_522_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1595 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1600 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1606 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln220_fu_548_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln220_reg_1611 : STD_LOGIC_VECTOR (1 downto 0);
    signal q_err_3rd_local_fu_552_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal q_err_3rd_local_reg_1616 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_load81_reg_1621 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_170_load_reg_1626 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_reg_1632 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_689_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1637 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_1642 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1648 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln220_1_fu_715_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln220_1_reg_1653 : STD_LOGIC_VECTOR (1 downto 0);
    signal q_err_3rd_local_1_fu_719_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal q_err_3rd_local_1_reg_1658 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_load_reg_1663 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_272_load_reg_1668 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_10_reg_1674 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_856_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_reg_1679 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_1684 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1690 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln220_2_fu_882_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln220_2_reg_1695 : STD_LOGIC_VECTOR (1 downto 0);
    signal q_err_3rd_local_2_fu_886_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal q_err_3rd_local_2_reg_1700 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_reg_pp0_iter0_read_word_1_reg_282 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter1_read_word_1_reg_282 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter2_read_word_1_reg_282 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_phi_reg_pp0_iter3_read_word_1_reg_282 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln182_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal idxprom233_fu_946_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_126 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln230_1_fu_576_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal p_0_0_045228_fu_130 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln226_fu_1043_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_27_fu_134 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln230_3_fu_743_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_0_0_0452_132_fu_138 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln226_1_fu_1184_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_28_fu_142 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln230_5_fu_904_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_0_0_0452_236_fu_146 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln226_2_fu_1325_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal conv_i5868_fu_150 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln230_fu_569_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_170_fu_154 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln230_2_fu_736_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv_i58_272_fu_158 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln230_4_fu_897_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal col_index_1_fu_162 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln182_fu_394_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal indvar_flatten_fu_166 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln177_1_fu_345_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln182_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln177_fu_359_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln213_2_fu_410_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln213_5_fu_414_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln213_8_fu_418_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln209_fu_432_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_436_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_436_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln209_4_fu_444_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln209_fu_432_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal q_2nd_err_scale7_fu_448_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal in_pixel_fu_428_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal q_2nd_err_scale7by16_fu_454_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln213_fu_467_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln213_1_fu_471_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln213_fu_489_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln213_fu_464_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln213_fu_475_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln212_fu_501_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln213_1_fu_479_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal quatizer_in_fu_495_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln212_1_fu_506_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln209_1_fu_593_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_597_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_fu_597_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln209_6_fu_605_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln209_1_fu_593_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal q_2nd_err_scale7_1_fu_609_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal in_pixel_1_fu_583_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal q_2nd_err_scale7by16_1_fu_615_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln213_1_fu_628_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln213_3_fu_632_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln213_2_fu_656_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln213_2_fu_625_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln213_3_fu_636_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln212_2_fu_668_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln213_4_fu_646_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal quatizer_in_1_fu_662_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln212_3_fu_673_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln209_2_fu_760_p0 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_764_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_17_fu_764_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln209_8_fu_772_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln209_2_fu_760_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal q_2nd_err_scale7_2_fu_776_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal in_pixel_2_fu_750_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal q_2nd_err_scale7by16_2_fu_782_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln213_2_fu_795_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln213_5_fu_799_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln213_4_fu_823_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln213_4_fu_792_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln213_6_fu_803_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln212_4_fu_835_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln213_7_fu_813_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal quatizer_in_2_fu_829_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln212_5_fu_840_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal sub232_fu_941_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln217_fu_956_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln217_1_fu_959_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln1_fu_972_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln225_1_fu_989_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln225_3_fu_997_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_2_fu_986_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_fu_979_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln209_3_fu_953_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln225_fu_1007_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_1_fu_983_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln225_fu_1001_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln225_1_fu_1017_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_5_fu_1023_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln225_4_fu_1013_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sum_tmp_fu_1027_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_4_fu_1033_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_tmp_fu_962_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_fu_1051_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln216_fu_967_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln244_fu_1059_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_1064_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln247_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln244_fu_1072_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln217_2_fu_1097_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln217_3_fu_1100_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln225_2_fu_1113_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln225_3_fu_1130_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln225_8_fu_1138_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_7_fu_1127_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_6_fu_1120_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln209_5_fu_1094_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln225_3_fu_1148_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_9_fu_1124_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln225_1_fu_1142_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln225_4_fu_1158_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_11_fu_1164_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln225_10_fu_1154_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sum_tmp_1_fu_1168_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_14_fu_1174_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_tmp_2_fu_1103_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_15_fu_1192_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln216_1_fu_1108_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln244_1_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_1205_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln247_1_fu_1221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln244_1_fu_1213_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln217_4_fu_1238_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln217_5_fu_1241_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln225_4_fu_1254_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_ln225_5_fu_1271_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal sext_ln225_13_fu_1279_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_12_fu_1268_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_14_fu_1261_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln209_7_fu_1235_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln225_6_fu_1289_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_15_fu_1265_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln225_2_fu_1283_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln225_7_fu_1299_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sext_ln225_17_fu_1305_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sext_ln225_16_fu_1295_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sum_tmp_2_fu_1309_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_20_fu_1315_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_tmp_4_fu_1244_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_1333_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln216_2_fu_1249_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln244_2_fu_1341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_1346_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln247_2_fu_1362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln244_2_fu_1354_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_5_fu_1368_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_3_fu_1227_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_tmp_1_fu_1086_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_52 : BOOLEAN;
    signal ap_enable_state2_pp0_iter1_stage0 : BOOLEAN;
    signal ap_enable_operation_66 : BOOLEAN;
    signal ap_enable_state3_pp0_iter2_stage0 : BOOLEAN;
    signal ap_enable_operation_180 : BOOLEAN;
    signal ap_enable_state5_pp0_iter4_stage0 : BOOLEAN;
    signal ap_enable_operation_55 : BOOLEAN;
    signal ap_enable_operation_68 : BOOLEAN;
    signal ap_enable_operation_209 : BOOLEAN;
    signal ap_enable_operation_58 : BOOLEAN;
    signal ap_enable_operation_70 : BOOLEAN;
    signal ap_enable_operation_238 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component QuantizationDithering_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component QuantizationDithering_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter3_read_word_1_reg_282_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                if (((icmp_ln191_reg_1508 = ap_const_lv1_1) and (icmp_ln177_reg_1499 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_read_word_1_reg_282 <= img0_data_dout;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_read_word_1_reg_282 <= ap_phi_reg_pp0_iter2_read_word_1_reg_282;
                end if;
            end if; 
        end if;
    end process;

    col_index_1_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    col_index_1_fu_162 <= ap_const_lv12_0;
                elsif (((icmp_ln177_fu_340_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    col_index_1_fu_162 <= add_ln182_fu_394_p2;
                end if;
            end if; 
        end if;
    end process;

    conv_i5868_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    conv_i5868_fu_150 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    conv_i5868_fu_150 <= select_ln230_fu_569_p3;
                end if;
            end if; 
        end if;
    end process;

    conv_i58_170_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    conv_i58_170_fu_154 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    conv_i58_170_fu_154 <= select_ln230_2_fu_736_p3;
                end if;
            end if; 
        end if;
    end process;

    conv_i58_272_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    conv_i58_272_fu_158 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    conv_i58_272_fu_158 <= select_ln230_4_fu_897_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_27_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_27_fu_134 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    empty_27_fu_134 <= select_ln230_3_fu_743_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_28_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_28_fu_142 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    empty_28_fu_142 <= select_ln230_5_fu_904_p3;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_fu_126 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    empty_fu_126 <= select_ln230_1_fu_576_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_166 <= ap_const_lv21_0;
                elsif (((icmp_ln177_fu_340_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_166 <= add_ln177_1_fu_345_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                icmp_ln177_reg_1499 <= icmp_ln177_fu_340_p2;
                    zext_ln109_cast_reg_1494(10 downto 0) <= zext_ln109_cast_fu_293_p1(10 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                cmp221_reg_1512_pp0_iter2_reg <= cmp221_reg_1512;
                cmp221_reg_1512_pp0_iter3_reg <= cmp221_reg_1512_pp0_iter2_reg;
                cmp239_reg_1516_pp0_iter2_reg <= cmp239_reg_1516;
                cmp239_reg_1516_pp0_iter3_reg <= cmp239_reg_1516_pp0_iter2_reg;
                conv_i5868_load_reg_1584 <= conv_i5868_fu_150;
                conv_i58_170_load_reg_1626 <= conv_i58_170_fu_154;
                conv_i58_272_load_reg_1668 <= conv_i58_272_fu_158;
                icmp_ln191_reg_1508_pp0_iter2_reg <= icmp_ln191_reg_1508;
                icmp_ln191_reg_1508_pp0_iter3_reg <= icmp_ln191_reg_1508_pp0_iter2_reg;
                p_load81_reg_1621 <= empty_27_fu_134;
                p_load82_reg_1579 <= empty_fu_126;
                p_load_reg_1663 <= empty_28_fu_142;
                q_err_3rd_local_1_reg_1658 <= q_err_3rd_local_1_fu_719_p3;
                q_err_3rd_local_2_reg_1700 <= q_err_3rd_local_2_fu_886_p3;
                q_err_3rd_local_reg_1616 <= q_err_3rd_local_fu_552_p3;
                tmp1_reg_1590 <= quatizer_in_fu_495_p2(9 downto 2);
                tmp_10_reg_1674 <= quatizer_in_2_fu_829_p2(9 downto 2);
                tmp_11_reg_1642 <= add_ln212_3_fu_673_p2(1 downto 1);
                tmp_12_reg_1690 <= quatizer_in_2_fu_829_p2(8 downto 2);
                tmp_18_reg_1679 <= add_ln212_5_fu_840_p2(1 downto 1);
                tmp_19_reg_1684 <= add_ln212_5_fu_840_p2(1 downto 1);
                tmp_1_reg_1632 <= quatizer_in_1_fu_662_p2(9 downto 2);
                tmp_2_reg_1595 <= add_ln212_1_fu_506_p2(1 downto 1);
                tmp_3_reg_1600 <= add_ln212_1_fu_506_p2(1 downto 1);
                tmp_6_reg_1606 <= quatizer_in_fu_495_p2(8 downto 2);
                tmp_9_reg_1637 <= add_ln212_3_fu_673_p2(1 downto 1);
                tmp_s_reg_1648 <= quatizer_in_1_fu_662_p2(8 downto 2);
                trunc_ln191_reg_1503_pp0_iter2_reg <= trunc_ln191_reg_1503;
                trunc_ln191_reg_1503_pp0_iter3_reg <= trunc_ln191_reg_1503_pp0_iter2_reg;
                trunc_ln213_2_reg_1554 <= trunc_ln213_2_fu_410_p1;
                trunc_ln213_5_reg_1564 <= trunc_ln213_5_fu_414_p1;
                trunc_ln213_8_reg_1574 <= trunc_ln213_8_fu_418_p1;
                trunc_ln220_1_reg_1653 <= trunc_ln220_1_fu_715_p1;
                trunc_ln220_2_reg_1695 <= trunc_ln220_2_fu_882_p1;
                trunc_ln220_reg_1611 <= trunc_ln220_fu_548_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_read_word_1_reg_282 <= ap_phi_reg_pp0_iter0_read_word_1_reg_282;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_read_word_1_reg_282 <= ap_phi_reg_pp0_iter1_read_word_1_reg_282;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln177_fu_340_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                cmp221_reg_1512 <= cmp221_fu_383_p2;
                cmp239_reg_1516 <= cmp239_fu_389_p2;
                icmp_ln191_reg_1508 <= icmp_ln191_fu_378_p2;
                trunc_ln191_reg_1503 <= trunc_ln191_fu_374_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                offset_buffer_1_load_reg_1559 <= offset_buffer_1_q1;
                offset_buffer_2_load_reg_1569 <= offset_buffer_2_q1;
                offset_buffer_load_reg_1549 <= offset_buffer_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                p_0_0_045228_fu_130 <= sext_ln226_fu_1043_p1;
                p_0_0_0452_132_fu_138 <= sext_ln226_1_fu_1184_p1;
                p_0_0_0452_236_fu_146 <= sext_ln226_2_fu_1325_p1;
            end if;
        end if;
    end process;
    zext_ln109_cast_reg_1494(11) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln177_1_fu_345_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_166) + unsigned(ap_const_lv21_1));
    add_ln182_fu_394_p2 <= std_logic_vector(unsigned(select_ln177_fu_359_p3) + unsigned(ap_const_lv12_1));
    add_ln212_1_fu_506_p2 <= std_logic_vector(unsigned(add_ln212_fu_501_p2) + unsigned(trunc_ln213_1_fu_479_p4));
    add_ln212_2_fu_668_p2 <= std_logic_vector(unsigned(trunc_ln213_3_fu_636_p4) + unsigned(trunc_ln213_5_reg_1564));
    add_ln212_3_fu_673_p2 <= std_logic_vector(unsigned(add_ln212_2_fu_668_p2) + unsigned(trunc_ln213_4_fu_646_p4));
    add_ln212_4_fu_835_p2 <= std_logic_vector(unsigned(trunc_ln213_6_fu_803_p4) + unsigned(trunc_ln213_8_reg_1574));
    add_ln212_5_fu_840_p2 <= std_logic_vector(unsigned(add_ln212_4_fu_835_p2) + unsigned(trunc_ln213_7_fu_813_p4));
    add_ln212_fu_501_p2 <= std_logic_vector(unsigned(trunc_ln213_fu_475_p1) + unsigned(trunc_ln213_2_reg_1554));
    add_ln213_2_fu_656_p2 <= std_logic_vector(unsigned(zext_ln213_1_fu_628_p1) + unsigned(sext_ln213_3_fu_632_p1));
    add_ln213_4_fu_823_p2 <= std_logic_vector(unsigned(zext_ln213_2_fu_795_p1) + unsigned(sext_ln213_5_fu_799_p1));
    add_ln213_fu_489_p2 <= std_logic_vector(unsigned(zext_ln213_fu_467_p1) + unsigned(sext_ln213_1_fu_471_p1));
    add_ln216_1_fu_1108_p2 <= std_logic_vector(unsigned(tmp_s_reg_1648) + unsigned(zext_ln217_3_fu_1100_p1));
    add_ln216_2_fu_1249_p2 <= std_logic_vector(unsigned(tmp_12_reg_1690) + unsigned(zext_ln217_5_fu_1241_p1));
    add_ln216_fu_967_p2 <= std_logic_vector(unsigned(tmp_6_reg_1606) + unsigned(zext_ln217_1_fu_959_p1));
    add_ln225_1_fu_1017_p2 <= std_logic_vector(signed(sext_ln225_1_fu_983_p1) + signed(sub_ln225_fu_1001_p2));
    add_ln225_3_fu_1148_p2 <= std_logic_vector(signed(sext_ln225_6_fu_1120_p1) + signed(sext_ln209_5_fu_1094_p1));
    add_ln225_4_fu_1158_p2 <= std_logic_vector(signed(sext_ln225_9_fu_1124_p1) + signed(sub_ln225_1_fu_1142_p2));
    add_ln225_6_fu_1289_p2 <= std_logic_vector(signed(sext_ln225_14_fu_1261_p1) + signed(sext_ln209_7_fu_1235_p1));
    add_ln225_7_fu_1299_p2 <= std_logic_vector(signed(sext_ln225_15_fu_1265_p1) + signed(sub_ln225_2_fu_1283_p2));
    add_ln225_fu_1007_p2 <= std_logic_vector(signed(sext_ln225_fu_979_p1) + signed(sext_ln209_3_fu_953_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, img0_data_empty_n, ap_predicate_op64_read_state3, img1_data_full_n, icmp_ln191_reg_1508_pp0_iter3_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((icmp_ln191_reg_1508_pp0_iter3_reg = ap_const_lv1_1) and (img1_data_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_predicate_op64_read_state3 = ap_const_boolean_1) and (img0_data_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, img0_data_empty_n, ap_predicate_op64_read_state3, img1_data_full_n, icmp_ln191_reg_1508_pp0_iter3_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((icmp_ln191_reg_1508_pp0_iter3_reg = ap_const_lv1_1) and (img1_data_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_predicate_op64_read_state3 = ap_const_boolean_1) and (img0_data_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter4, img0_data_empty_n, ap_predicate_op64_read_state3, img1_data_full_n, icmp_ln191_reg_1508_pp0_iter3_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((icmp_ln191_reg_1508_pp0_iter3_reg = ap_const_lv1_1) and (img1_data_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_predicate_op64_read_state3 = ap_const_boolean_1) and (img0_data_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter2_assign_proc : process(img0_data_empty_n, ap_predicate_op64_read_state3)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((ap_predicate_op64_read_state3 = ap_const_boolean_1) and (img0_data_empty_n = ap_const_logic_0));
    end process;

        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter4_assign_proc : process(img1_data_full_n, icmp_ln191_reg_1508_pp0_iter3_reg)
    begin
                ap_block_state5_pp0_stage0_iter4 <= ((icmp_ln191_reg_1508_pp0_iter3_reg = ap_const_lv1_1) and (img1_data_full_n = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln177_fu_340_p2)
    begin
        if (((icmp_ln177_fu_340_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_enable_operation_180_assign_proc : process(cmp221_reg_1512_pp0_iter3_reg)
    begin
                ap_enable_operation_180 <= (cmp221_reg_1512_pp0_iter3_reg = ap_const_lv1_1);
    end process;


    ap_enable_operation_209_assign_proc : process(cmp221_reg_1512_pp0_iter3_reg)
    begin
                ap_enable_operation_209 <= (cmp221_reg_1512_pp0_iter3_reg = ap_const_lv1_1);
    end process;


    ap_enable_operation_238_assign_proc : process(cmp221_reg_1512_pp0_iter3_reg)
    begin
                ap_enable_operation_238 <= (cmp221_reg_1512_pp0_iter3_reg = ap_const_lv1_1);
    end process;


    ap_enable_operation_52_assign_proc : process(icmp_ln177_fu_340_p2)
    begin
                ap_enable_operation_52 <= (icmp_ln177_fu_340_p2 = ap_const_lv1_0);
    end process;


    ap_enable_operation_55_assign_proc : process(icmp_ln177_fu_340_p2)
    begin
                ap_enable_operation_55 <= (icmp_ln177_fu_340_p2 = ap_const_lv1_0);
    end process;


    ap_enable_operation_58_assign_proc : process(icmp_ln177_fu_340_p2)
    begin
                ap_enable_operation_58 <= (icmp_ln177_fu_340_p2 = ap_const_lv1_0);
    end process;

        ap_enable_operation_66 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_68 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_70 <= (ap_const_boolean_1 = ap_const_boolean_1);
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state2_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state2_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state3_pp0_iter2_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter2)
    begin
                ap_enable_state3_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state5_pp0_iter4_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4)
    begin
                ap_enable_state5_pp0_iter4_stage0 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_phi_reg_pp0_iter0_read_word_1_reg_282 <= "XXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op64_read_state3_assign_proc : process(icmp_ln177_reg_1499, icmp_ln191_reg_1508)
    begin
                ap_predicate_op64_read_state3 <= ((icmp_ln191_reg_1508 = ap_const_lv1_1) and (icmp_ln177_reg_1499 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cmp221_fu_383_p2 <= "0" when (select_ln177_fu_359_p3 = ap_const_lv12_0) else "1";
    cmp239_fu_389_p2 <= "1" when (width = trunc_ln191_fu_374_p1) else "0";
    icmp_ln177_fu_340_p2 <= "1" when (indvar_flatten_fu_166 = mul_ln177) else "0";
    icmp_ln182_fu_354_p2 <= "1" when (col_index_1_fu_162 = add_ln177) else "0";
    icmp_ln191_fu_378_p2 <= "1" when (signed(select_ln177_fu_359_p3) < signed(zext_ln109_cast_reg_1494)) else "0";
    idxprom233_fu_946_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sub232_fu_941_p2),64));

    img0_data_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, img0_data_empty_n, ap_predicate_op64_read_state3, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op64_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            img0_data_blk_n <= img0_data_empty_n;
        else 
            img0_data_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img0_data_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op64_read_state3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op64_read_state3 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            img0_data_read <= ap_const_logic_1;
        else 
            img0_data_read <= ap_const_logic_0;
        end if; 
    end process;


    img1_data_blk_n_assign_proc : process(ap_enable_reg_pp0_iter4, img1_data_full_n, icmp_ln191_reg_1508_pp0_iter3_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln191_reg_1508_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            img1_data_blk_n <= img1_data_full_n;
        else 
            img1_data_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img1_data_din <= ((out_tmp_5_fu_1368_p3 & out_tmp_3_fu_1227_p3) & out_tmp_1_fu_1086_p3);

    img1_data_write_assign_proc : process(ap_enable_reg_pp0_iter4, icmp_ln191_reg_1508_pp0_iter3_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln191_reg_1508_pp0_iter3_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            img1_data_write <= ap_const_logic_1;
        else 
            img1_data_write <= ap_const_logic_0;
        end if; 
    end process;

    in_pixel_1_fu_583_p4 <= ap_phi_reg_pp0_iter3_read_word_1_reg_282(15 downto 8);
    in_pixel_2_fu_750_p4 <= ap_phi_reg_pp0_iter3_read_word_1_reg_282(23 downto 16);
    in_pixel_fu_428_p1 <= ap_phi_reg_pp0_iter3_read_word_1_reg_282(8 - 1 downto 0);
    offset_buffer_1_address0 <= idxprom233_fu_946_p1(11 - 1 downto 0);
    offset_buffer_1_address1 <= zext_ln182_fu_367_p1(11 - 1 downto 0);

    offset_buffer_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            offset_buffer_1_ce0 <= ap_const_logic_1;
        else 
            offset_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            offset_buffer_1_ce1 <= ap_const_logic_1;
        else 
            offset_buffer_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_1_d0 <= p_0_0_0452_132_fu_138;

    offset_buffer_1_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, cmp221_reg_1512_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (cmp221_reg_1512_pp0_iter3_reg = ap_const_lv1_1))) then 
            offset_buffer_1_we0 <= ap_const_logic_1;
        else 
            offset_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_2_address0 <= idxprom233_fu_946_p1(11 - 1 downto 0);
    offset_buffer_2_address1 <= zext_ln182_fu_367_p1(11 - 1 downto 0);

    offset_buffer_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            offset_buffer_2_ce0 <= ap_const_logic_1;
        else 
            offset_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            offset_buffer_2_ce1 <= ap_const_logic_1;
        else 
            offset_buffer_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_2_d0 <= p_0_0_0452_236_fu_146;

    offset_buffer_2_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, cmp221_reg_1512_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (cmp221_reg_1512_pp0_iter3_reg = ap_const_lv1_1))) then 
            offset_buffer_2_we0 <= ap_const_logic_1;
        else 
            offset_buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_address0 <= idxprom233_fu_946_p1(11 - 1 downto 0);
    offset_buffer_address1 <= zext_ln182_fu_367_p1(11 - 1 downto 0);

    offset_buffer_ce0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            offset_buffer_ce0 <= ap_const_logic_1;
        else 
            offset_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            offset_buffer_ce1 <= ap_const_logic_1;
        else 
            offset_buffer_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    offset_buffer_d0 <= p_0_0_045228_fu_130;

    offset_buffer_we0_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001, cmp221_reg_1512_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (cmp221_reg_1512_pp0_iter3_reg = ap_const_lv1_1))) then 
            offset_buffer_we0 <= ap_const_logic_1;
        else 
            offset_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    or_ln244_1_fu_1200_p2 <= (tmp_15_fu_1192_p3 or cmp239_reg_1516_pp0_iter3_reg);
    or_ln244_2_fu_1341_p2 <= (tmp_21_fu_1333_p3 or cmp239_reg_1516_pp0_iter3_reg);
    or_ln244_fu_1059_p2 <= (tmp_5_fu_1051_p3 or cmp239_reg_1516_pp0_iter3_reg);
    or_ln247_1_fu_1221_p2 <= (tmp_16_fu_1205_p3 or or_ln244_1_fu_1200_p2);
    or_ln247_2_fu_1362_p2 <= (tmp_22_fu_1346_p3 or or_ln244_2_fu_1341_p2);
    or_ln247_fu_1080_p2 <= (tmp_7_fu_1064_p3 or or_ln244_fu_1059_p2);
    out_tmp_1_fu_1086_p3 <= 
        select_ln244_fu_1072_p3 when (or_ln247_fu_1080_p2(0) = '1') else 
        out_tmp_fu_962_p2;
    out_tmp_2_fu_1103_p2 <= std_logic_vector(unsigned(tmp_1_reg_1632) + unsigned(zext_ln217_2_fu_1097_p1));
    out_tmp_3_fu_1227_p3 <= 
        select_ln244_1_fu_1213_p3 when (or_ln247_1_fu_1221_p2(0) = '1') else 
        out_tmp_2_fu_1103_p2;
    out_tmp_4_fu_1244_p2 <= std_logic_vector(unsigned(tmp_10_reg_1674) + unsigned(zext_ln217_4_fu_1238_p1));
    out_tmp_5_fu_1368_p3 <= 
        select_ln244_2_fu_1354_p3 when (or_ln247_2_fu_1362_p2(0) = '1') else 
        out_tmp_4_fu_1244_p2;
    out_tmp_fu_962_p2 <= std_logic_vector(unsigned(tmp1_reg_1590) + unsigned(zext_ln217_fu_956_p1));
    q_2nd_err_scale7_1_fu_609_p2 <= std_logic_vector(signed(sext_ln209_6_fu_605_p1) - signed(sext_ln209_1_fu_593_p1));
    q_2nd_err_scale7_2_fu_776_p2 <= std_logic_vector(signed(sext_ln209_8_fu_772_p1) - signed(sext_ln209_2_fu_760_p1));
    q_2nd_err_scale7_fu_448_p2 <= std_logic_vector(signed(sext_ln209_4_fu_444_p1) - signed(sext_ln209_fu_432_p1));
    q_2nd_err_scale7by16_1_fu_615_p4 <= q_2nd_err_scale7_1_fu_609_p2(9 downto 4);
    q_2nd_err_scale7by16_2_fu_782_p4 <= q_2nd_err_scale7_2_fu_776_p2(9 downto 4);
    q_2nd_err_scale7by16_fu_454_p4 <= q_2nd_err_scale7_fu_448_p2(9 downto 4);
    q_err_3rd_local_1_fu_719_p3 <= (tmp_9_fu_689_p3 & trunc_ln220_1_fu_715_p1);
    q_err_3rd_local_2_fu_886_p3 <= (tmp_18_fu_856_p3 & trunc_ln220_2_fu_882_p1);
    q_err_3rd_local_fu_552_p3 <= (tmp_2_fu_522_p3 & trunc_ln220_fu_548_p1);
    quatizer_in_1_fu_662_p2 <= std_logic_vector(unsigned(add_ln213_2_fu_656_p2) + unsigned(sext_ln213_2_fu_625_p1));
    quatizer_in_2_fu_829_p2 <= std_logic_vector(unsigned(add_ln213_4_fu_823_p2) + unsigned(sext_ln213_4_fu_792_p1));
    quatizer_in_fu_495_p2 <= std_logic_vector(unsigned(add_ln213_fu_489_p2) + unsigned(sext_ln213_fu_464_p1));
    select_ln177_fu_359_p3 <= 
        ap_const_lv12_0 when (icmp_ln182_fu_354_p2(0) = '1') else 
        col_index_1_fu_162;
    select_ln230_1_fu_576_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1516_pp0_iter2_reg(0) = '1') else 
        conv_i5868_fu_150;
    select_ln230_2_fu_736_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1516_pp0_iter2_reg(0) = '1') else 
        q_err_3rd_local_1_fu_719_p3;
    select_ln230_3_fu_743_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1516_pp0_iter2_reg(0) = '1') else 
        conv_i58_170_fu_154;
    select_ln230_4_fu_897_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1516_pp0_iter2_reg(0) = '1') else 
        q_err_3rd_local_2_fu_886_p3;
    select_ln230_5_fu_904_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1516_pp0_iter2_reg(0) = '1') else 
        conv_i58_272_fu_158;
    select_ln230_fu_569_p3 <= 
        ap_const_lv3_0 when (cmp239_reg_1516_pp0_iter2_reg(0) = '1') else 
        q_err_3rd_local_fu_552_p3;
    select_ln244_1_fu_1213_p3 <= 
        ap_const_lv8_0 when (or_ln244_1_fu_1200_p2(0) = '1') else 
        ap_const_lv8_3F;
    select_ln244_2_fu_1354_p3 <= 
        ap_const_lv8_0 when (or_ln244_2_fu_1341_p2(0) = '1') else 
        ap_const_lv8_3F;
    select_ln244_fu_1072_p3 <= 
        ap_const_lv8_0 when (or_ln244_fu_1059_p2(0) = '1') else 
        ap_const_lv8_3F;
    sext_ln209_1_fu_593_p0 <= conv_i58_170_fu_154;
        sext_ln209_1_fu_593_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln209_1_fu_593_p0),10));

    sext_ln209_2_fu_760_p0 <= conv_i58_272_fu_158;
        sext_ln209_2_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln209_2_fu_760_p0),10));

        sext_ln209_3_fu_953_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i5868_load_reg_1584),6));

        sext_ln209_4_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_436_p3),10));

        sext_ln209_5_fu_1094_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i58_170_load_reg_1626),6));

        sext_ln209_6_fu_605_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_8_fu_597_p3),10));

        sext_ln209_7_fu_1235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(conv_i58_272_load_reg_1668),6));

        sext_ln209_8_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_764_p3),10));

    sext_ln209_fu_432_p0 <= conv_i5868_fu_150;
        sext_ln209_fu_432_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln209_fu_432_p0),10));

        sext_ln213_1_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_2nd_err_scale7by16_fu_454_p4),10));

        sext_ln213_2_fu_625_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_buffer_1_load_reg_1559),10));

        sext_ln213_3_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_2nd_err_scale7by16_1_fu_615_p4),10));

        sext_ln213_4_fu_792_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_buffer_2_load_reg_1569),10));

        sext_ln213_5_fu_799_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_2nd_err_scale7by16_2_fu_782_p4),10));

        sext_ln213_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(offset_buffer_load_reg_1549),10));

        sext_ln225_10_fu_1154_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln225_3_fu_1148_p2),7));

        sext_ln225_11_fu_1164_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln225_4_fu_1158_p2),7));

        sext_ln225_12_fu_1268_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_err_3rd_local_2_reg_1700),6));

        sext_ln225_13_fu_1279_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln225_5_fu_1271_p4),6));

        sext_ln225_14_fu_1261_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln225_4_fu_1254_p3),6));

        sext_ln225_15_fu_1265_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_load_reg_1663),6));

        sext_ln225_16_fu_1295_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln225_6_fu_1289_p2),7));

        sext_ln225_17_fu_1305_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln225_7_fu_1299_p2),7));

        sext_ln225_1_fu_983_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_load82_reg_1579),6));

        sext_ln225_2_fu_986_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_err_3rd_local_reg_1616),6));

        sext_ln225_3_fu_997_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln225_1_fu_989_p4),6));

        sext_ln225_4_fu_1013_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln225_fu_1007_p2),7));

        sext_ln225_5_fu_1023_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln225_1_fu_1017_p2),7));

        sext_ln225_6_fu_1120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln225_2_fu_1113_p3),6));

        sext_ln225_7_fu_1127_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(q_err_3rd_local_1_reg_1658),6));

        sext_ln225_8_fu_1138_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln225_3_fu_1130_p4),6));

        sext_ln225_9_fu_1124_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_load81_reg_1621),6));

        sext_ln225_fu_979_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln1_fu_972_p3),6));

        sext_ln226_1_fu_1184_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_14_fu_1174_p4),7));

        sext_ln226_2_fu_1325_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_20_fu_1315_p4),7));

        sext_ln226_fu_1043_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_4_fu_1033_p4),7));

    shl_ln1_fu_972_p3 <= (conv_i5868_load_reg_1584 & ap_const_lv2_0);
    shl_ln225_1_fu_989_p4 <= ((tmp_2_reg_1595 & trunc_ln220_reg_1611) & ap_const_lv2_0);
    shl_ln225_2_fu_1113_p3 <= (conv_i58_170_load_reg_1626 & ap_const_lv2_0);
    shl_ln225_3_fu_1130_p4 <= ((tmp_9_reg_1637 & trunc_ln220_1_reg_1653) & ap_const_lv2_0);
    shl_ln225_4_fu_1254_p3 <= (conv_i58_272_load_reg_1668 & ap_const_lv2_0);
    shl_ln225_5_fu_1271_p4 <= ((tmp_18_reg_1679 & trunc_ln220_2_reg_1695) & ap_const_lv2_0);
    sub232_fu_941_p2 <= std_logic_vector(unsigned(trunc_ln191_reg_1503_pp0_iter3_reg) + unsigned(ap_const_lv11_7FF));
    sub_ln225_1_fu_1142_p2 <= std_logic_vector(signed(sext_ln225_8_fu_1138_p1) - signed(sext_ln225_7_fu_1127_p1));
    sub_ln225_2_fu_1283_p2 <= std_logic_vector(signed(sext_ln225_13_fu_1279_p1) - signed(sext_ln225_12_fu_1268_p1));
    sub_ln225_fu_1001_p2 <= std_logic_vector(signed(sext_ln225_3_fu_997_p1) - signed(sext_ln225_2_fu_986_p1));
    sum_tmp_1_fu_1168_p2 <= std_logic_vector(signed(sext_ln225_11_fu_1164_p1) + signed(sext_ln225_10_fu_1154_p1));
    sum_tmp_2_fu_1309_p2 <= std_logic_vector(signed(sext_ln225_17_fu_1305_p1) + signed(sext_ln225_16_fu_1295_p1));
    sum_tmp_fu_1027_p2 <= std_logic_vector(signed(sext_ln225_5_fu_1023_p1) + signed(sext_ln225_4_fu_1013_p1));
    tmp_14_fu_1174_p4 <= sum_tmp_1_fu_1168_p2(6 downto 4);
    tmp_15_fu_1192_p3 <= out_tmp_2_fu_1103_p2(7 downto 7);
    tmp_16_fu_1205_p3 <= add_ln216_1_fu_1108_p2(6 downto 6);
    tmp_17_fu_764_p1 <= conv_i58_272_fu_158;
    tmp_17_fu_764_p3 <= (tmp_17_fu_764_p1 & ap_const_lv3_0);
    tmp_18_fu_856_p3 <= add_ln212_5_fu_840_p2(1 downto 1);
    tmp_20_fu_1315_p4 <= sum_tmp_2_fu_1309_p2(6 downto 4);
    tmp_21_fu_1333_p3 <= out_tmp_4_fu_1244_p2(7 downto 7);
    tmp_22_fu_1346_p3 <= add_ln216_2_fu_1249_p2(6 downto 6);
    tmp_2_fu_522_p3 <= add_ln212_1_fu_506_p2(1 downto 1);
    tmp_4_fu_1033_p4 <= sum_tmp_fu_1027_p2(6 downto 4);
    tmp_5_fu_1051_p3 <= out_tmp_fu_962_p2(7 downto 7);
    tmp_7_fu_1064_p3 <= add_ln216_fu_967_p2(6 downto 6);
    tmp_8_fu_597_p1 <= conv_i58_170_fu_154;
    tmp_8_fu_597_p3 <= (tmp_8_fu_597_p1 & ap_const_lv3_0);
    tmp_9_fu_689_p3 <= add_ln212_3_fu_673_p2(1 downto 1);
    tmp_fu_436_p1 <= conv_i5868_fu_150;
    tmp_fu_436_p3 <= (tmp_fu_436_p1 & ap_const_lv3_0);
    trunc_ln191_fu_374_p1 <= select_ln177_fu_359_p3(11 - 1 downto 0);
    trunc_ln213_1_fu_479_p4 <= q_2nd_err_scale7_fu_448_p2(5 downto 4);
    trunc_ln213_2_fu_410_p0 <= offset_buffer_q1;
    trunc_ln213_2_fu_410_p1 <= trunc_ln213_2_fu_410_p0(2 - 1 downto 0);
    trunc_ln213_3_fu_636_p4 <= ap_phi_reg_pp0_iter3_read_word_1_reg_282(9 downto 8);
    trunc_ln213_4_fu_646_p4 <= q_2nd_err_scale7_1_fu_609_p2(5 downto 4);
    trunc_ln213_5_fu_414_p0 <= offset_buffer_1_q1;
    trunc_ln213_5_fu_414_p1 <= trunc_ln213_5_fu_414_p0(2 - 1 downto 0);
    trunc_ln213_6_fu_803_p4 <= ap_phi_reg_pp0_iter3_read_word_1_reg_282(17 downto 16);
    trunc_ln213_7_fu_813_p4 <= q_2nd_err_scale7_2_fu_776_p2(5 downto 4);
    trunc_ln213_8_fu_418_p0 <= offset_buffer_2_q1;
    trunc_ln213_8_fu_418_p1 <= trunc_ln213_8_fu_418_p0(2 - 1 downto 0);
    trunc_ln213_fu_475_p1 <= ap_phi_reg_pp0_iter3_read_word_1_reg_282(2 - 1 downto 0);
    trunc_ln220_1_fu_715_p1 <= quatizer_in_1_fu_662_p2(2 - 1 downto 0);
    trunc_ln220_2_fu_882_p1 <= quatizer_in_2_fu_829_p2(2 - 1 downto 0);
    trunc_ln220_fu_548_p1 <= quatizer_in_fu_495_p2(2 - 1 downto 0);
    zext_ln109_cast_fu_293_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln109),12));
    zext_ln182_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln177_fu_359_p3),64));
    zext_ln213_1_fu_628_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pixel_1_fu_583_p4),10));
    zext_ln213_2_fu_795_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pixel_2_fu_750_p4),10));
    zext_ln213_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_pixel_fu_428_p1),10));
    zext_ln217_1_fu_959_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_reg_1600),7));
    zext_ln217_2_fu_1097_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_reg_1642),8));
    zext_ln217_3_fu_1100_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_reg_1642),7));
    zext_ln217_4_fu_1238_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_reg_1684),8));
    zext_ln217_5_fu_1241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_reg_1684),7));
    zext_ln217_fu_956_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_reg_1600),8));
end behav;
