transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vmap -link {C:/Users/kenny/Desktop/hw/hw.cache/compile_simlib/riviera}
vlib riviera/xilinx_vip
vlib riviera/xpm
vlib riviera/xil_defaultlib
vlib riviera/fifo_generator_v13_2_8
vlib riviera/axis_infrastructure_v1_1_0
vlib riviera/axis_data_fifo_v2_0_10
vlib riviera/axi_infrastructure_v1_1_0
vlib riviera/axi_vip_v1_1_14
vlib riviera/processing_system7_vip_v1_0_16
vlib riviera/lib_cdc_v1_0_2
vlib riviera/proc_sys_reset_v5_0_13
vlib riviera/xlconcat_v2_1_4
vlib riviera/lib_pkg_v1_0_2
vlib riviera/lib_fifo_v1_0_17
vlib riviera/blk_mem_gen_v8_4_6
vlib riviera/lib_bmg_v1_0_15
vlib riviera/lib_srl_fifo_v1_0_2
vlib riviera/axi_datamover_v5_1_30
vlib riviera/axi_vdma_v6_3_16
vlib riviera/generic_baseblocks_v2_1_0
vlib riviera/axi_register_slice_v2_1_28
vlib riviera/axi_data_fifo_v2_1_27
vlib riviera/axi_crossbar_v2_1_29
vlib riviera/axi_lite_ipif_v3_0_4
vlib riviera/v_tc_v6_1_13
vlib riviera/v_vid_in_axi4s_v4_0_9
vlib riviera/v_axi4s_vid_out_v4_0_16
vlib riviera/v_tc_v6_2_6
vlib riviera/axis_register_slice_v1_1_28
vlib riviera/axis_switch_v1_1_28
vlib riviera/interrupt_control_v3_1_4
vlib riviera/axi_gpio_v2_0_30
vlib riviera/axi_protocol_converter_v2_1_28

vlog -work xilinx_vip  -incr "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"E:/VitisXilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"E:/VitisXilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  -incr \
"E:/VitisXilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ipshared/40b8/hdl/LineBuffer.vhd" \
"../../../bd/system/ipshared/40b8/hdl/AXI_BayerToRGB.vhd" \
"../../../bd/system/ip/system_AXI_BayerToRGB_0_0/sim/system_AXI_BayerToRGB_0_0.vhd" \
"../../../bd/system/ipshared/a507/hdl/StoredGammaCoefs.vhd" \
"../../../bd/system/ipshared/a507/hdl/AXI_GammaCorrection.vhd" \
"../../../bd/system/ip/system_AXI_GammaCorrection_1_0/sim/system_AXI_GammaCorrection_1_0.vhd" \
"../../../bd/system/ip/system_DVIClocking_1_0/sim/system_DVIClocking_1_0.vhd" \

vlog -work fifo_generator_v13_2_8  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_8 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_8  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/cdc_fifo/sim/cdc_fifo.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/sim/ila_rxclk.vhd" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/sim/ila_rxclk_lane.vhd" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/sim/ila_vidclk.vhd" \

vlog -work axis_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_infrastructure_v1_1_vl_rfs.v" \

vlog -work axis_data_fifo_v2_0_10  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl/axis_data_fifo_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/sim/line_buffer.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ipshared/b799/hdl/CRC16_behavioral.vhd" \
"../../../bd/system/ipshared/b799/hdl/DebugLib.vhd" \
"../../../bd/system/ipshared/b799/hdl/ECC.vhd" \
"../../../bd/system/ipshared/b799/hdl/SyncAsync.vhd" \
"../../../bd/system/ipshared/b799/hdl/SyncAsyncReset.vhd" \
"../../../bd/system/ipshared/b799/hdl/LLP.vhd" \
"../../../bd/system/ipshared/b799/hdl/SimpleFIFO.vhd" \
"../../../bd/system/ipshared/b799/hdl/LM.vhd" \
"../../../bd/system/ipshared/b799/hdl/MIPI_CSI2_Rx.vhd" \
"../../../bd/system/ipshared/b799/hdl/MIPI_CSI_2_RX_v1_0_S_AXI_LITE.vhd" \
"../../../bd/system/ipshared/b799/hdl/MIPI_CSI2_RxTop.vhd" \
"../../../bd/system/ip/system_MIPI_CSI_2_RX_0_0/sim/system_MIPI_CSI_2_RX_0_0.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/sim/ila_sfen_rxclk.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/sim/ila_sfen_refclk.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/sim/ila_scnn_refclk.vhd" \
"../../../bd/system/ipshared/7858/hdl/DPHY_Pkg.vhd" \
"../../../bd/system/ipshared/7858/hdl/DebugLib.vhd" \
"../../../bd/system/ipshared/7858/hdl/HS_Deserializer.vhd" \
"../../../bd/system/ipshared/7858/hdl/GlitchFilter.vhd" \
"../../../bd/system/ipshared/7858/hdl/HS_Clocking.vhd" \
"../../../bd/system/ipshared/7858/hdl/InputBuffer.vhd" \
"../../../bd/system/ipshared/7858/hdl/DPHY_LaneSFEN.vhd" \
"../../../bd/system/ipshared/7858/hdl/DPHY_LaneSCNN.vhd" \
"../../../bd/system/ipshared/7858/hdl/S_AXI_Lite.vhd" \
"../../../bd/system/ipshared/7858/hdl/MIPI_DPHY_Receiver.vhd" \
"../../../bd/system/ip/system_MIPI_D_PHY_RX_0_0/sim/system_MIPI_D_PHY_RX_0_0.vhd" \

vlog -work axi_infrastructure_v1_1_0  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_14  -incr "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_16  -incr "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/d57c/src/ClockGen.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/d57c/src/SyncAsync.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/d57c/src/SyncAsyncReset.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/d57c/src/DVI_Constants.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/d57c/src/OutputSERDES.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/d57c/src/TMDS_Encoder.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/d57c/src/rgb2dvi.vhd" \
"../../../bd/system/ip/system_rgb2dvi_0_0/sim/system_rgb2dvi_0_0.vhd" \

vcom -work lib_cdc_v1_0_2 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_13 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ip/system_rst_clk_wiz_0_50M_0/sim/system_rst_clk_wiz_0_50M_0.vhd" \
"../../../bd/system/ip/system_rst_vid_clk_dyn_0/sim/system_rst_vid_clk_dyn_0.vhd" \

vlog -work xlconcat_v2_1_4  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \

vcom -work lib_pkg_v1_0_2 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vcom -work lib_fifo_v1_0_17 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/3d41/hdl/lib_fifo_v1_0_rfs.vhd" \

vlog -work blk_mem_gen_v8_4_6  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/bb55/simulation/blk_mem_gen_v8_4.v" \

vcom -work lib_bmg_v1_0_15 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/3f7c/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_30 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/e959/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vlog -work axi_vdma_v6_3_16  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl/axi_vdma_v6_3_rfs.v" \

vcom -work axi_vdma_v6_3_16 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl/axi_vdma_v6_3_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ip/system_axi_vdma_0_0/sim/system_axi_vdma_0_0.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \

vlog -work generic_baseblocks_v2_1_0  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_28  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_27  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_29  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \

vcom -work axi_lite_ipif_v3_0_4 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work v_tc_v6_1_13 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \

vlog -work v_vid_in_axi4s_v4_0_9  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \

vlog -work v_axi4s_vid_out_v4_0_16  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/c523/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
"../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_mmcm_pll_drp.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_conv_funs_pkg.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_proc_common_pkg.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_ipif_pkg.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_family_support.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_family.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_soft_reset.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/proc_common_v3_00_a/hdl/src/vhdl/system_video_dynclk_0_pselect_f.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_address_decoder.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_slave_attachment.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_video_dynclk_0_axi_lite_ipif.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_clk_wiz_drp.vhd" \
"../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_axi_clk_config.vhd" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0_clk_wiz.v" \
"../../../bd/system/ip/system_video_dynclk_0/system_video_dynclk_0.v" \

vcom -work v_tc_v6_2_6 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/0350/hdl/v_tc_v6_2_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ip/system_vtg_0/sim/system_vtg_0.vhd" \

vlog -work axis_register_slice_v1_1_28  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/eb9f/hdl/axis_register_slice_v1_1_vl_rfs.v" \

vlog -work axis_switch_v1_1_28  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/2f0f/hdl/axis_switch_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_axis_switch_0_0/sim/system_axis_switch_0_0.v" \
"../../../bd/system/ip/system_axis_switch_1_0/sim/system_axis_switch_1_0.v" \

vcom -work interrupt_control_v3_1_4 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_30 -93  -incr \
"../../../../hw.gen/sources_1/bd/system/ipshared/18b7/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/ip/system_axi_gpio_0_0/sim/system_axi_gpio_0_0.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_AXIvideo2xfMat_24_16_720_1280_1_2_Pipeline_loop_col_zxi2mat.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_AXIvideo2xfMat_24_16_720_1280_1_2_Pipeline_loop_last_hunt.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_AXIvideo2xfMat_24_16_720_1280_1_2_Pipeline_loop_start_hunt.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_AXIvideo2xfMat_24_16_720_1280_1_2_s.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_fifo_w10_d2_S.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_fifo_w11_d2_S.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_fifo_w24_d2_S.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_flow_control_loop_pipe_sequential_init.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_modefilter_3_1_16_720_1280_1_2_2_s.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_mux_3_2_2_1_1.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_mux_3_2_24_1_1.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_mux_9_4_8_1_0.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_regslice_both.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_start_for_modefilter_3_1_16_720_1280_1_2_2_U0.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_start_for_xfMat2AXIvideo_24_16_720_1280_1_2_U0.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xfMat2AXIvideo_24_16_720_1280_1_2_Pipeline_loop_col_mat2axi.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xfMat2AXIvideo_24_16_720_1280_1_2_s.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_buf_RAM_S2P_BRAM_1R1W.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter_xFModeProc_3_1_16_3_9_s.vhd" \
"../../../../hw.gen/sources_1/bd/system/ipshared/4f49/hdl/vhdl/ModeFilter.vhd" \
"../../../bd/system/ip/system_ModeFilter_0_0/sim/system_ModeFilter_0_0.vhd" \

vlog -work axi_protocol_converter_v2_1_28  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../../hw.gen/sources_1/bd/system/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -v2k5 "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/line_buffer/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/ec67/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/aed8/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/0691/hdl" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/30ef" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_vidclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk_lane/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_CSI_2_RX_0_0/hdl/ila_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_scnn_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_refclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ip/system_MIPI_D_PHY_RX_0_0/hdl/ila_sfen_rxclk/hdl/verilog" "+incdir+../../../../hw.gen/sources_1/bd/system/ipshared/8713/hdl" "+incdir+E:/VitisXilinx/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l xil_defaultlib -l fifo_generator_v13_2_8 -l axis_infrastructure_v1_1_0 -l axis_data_fifo_v2_0_10 -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l lib_cdc_v1_0_2 -l proc_sys_reset_v5_0_13 -l xlconcat_v2_1_4 -l lib_pkg_v1_0_2 -l lib_fifo_v1_0_17 -l blk_mem_gen_v8_4_6 -l lib_bmg_v1_0_15 -l lib_srl_fifo_v1_0_2 -l axi_datamover_v5_1_30 -l axi_vdma_v6_3_16 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l axi_lite_ipif_v3_0_4 -l v_tc_v6_1_13 -l v_vid_in_axi4s_v4_0_9 -l v_axi4s_vid_out_v4_0_16 -l v_tc_v6_2_6 -l axis_register_slice_v1_1_28 -l axis_switch_v1_1_28 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l axi_protocol_converter_v2_1_28 \
"../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
"../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
"../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \

vcom -work xil_defaultlib -93  -incr \
"../../../bd/system/sim/system.vhd" \

vlog -work xil_defaultlib \
"glbl.v"

