// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Otsu_xfOtsuKernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_hist_0_address0,
        p_hist_0_ce0,
        p_hist_0_q0,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] p_hist_0_address0;
output   p_hist_0_ce0;
input  [31:0] p_hist_0_q0;
output  [7:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] wdt_reg_503;
wire    ap_CS_fsm_state4;
wire   [6:0] trunc_ln50_fu_157_p1;
reg   [6:0] trunc_ln50_reg_510;
reg   [31:0] hgt_reg_515;
wire   [6:0] trunc_ln51_fu_169_p1;
reg   [6:0] trunc_ln51_reg_522;
wire   [0:0] icmp_ln53_fu_173_p2;
reg   [0:0] icmp_ln53_reg_527;
wire   [6:0] tmp_fu_179_p4;
reg   [6:0] tmp_reg_534;
wire   [0:0] icmp_ln56_fu_197_p2;
reg   [0:0] icmp_ln56_reg_539;
wire   [7:0] sub_ln57_fu_203_p2;
reg   [7:0] sub_ln57_reg_545;
wire   [0:0] icmp_ln60_fu_209_p2;
reg   [0:0] icmp_ln60_reg_550;
wire   [6:0] tmp_1_fu_215_p4;
reg   [6:0] tmp_1_reg_557;
wire   [0:0] icmp_ln63_fu_233_p2;
reg   [0:0] icmp_ln63_reg_562;
wire   [7:0] sub_ln64_fu_239_p2;
reg   [7:0] sub_ln64_reg_568;
wire   [31:0] wdt_4_fu_294_p3;
reg   [31:0] wdt_4_reg_573;
wire    ap_CS_fsm_state5;
wire  signed [31:0] hgt_4_fu_351_p3;
reg   [31:0] hgt_4_reg_580;
wire  signed [6:0] select_ln56_fu_359_p3;
reg   [6:0] select_ln56_reg_586;
wire  signed [6:0] select_ln63_fu_367_p3;
reg   [6:0] select_ln63_reg_592;
wire   [0:0] rev_fu_391_p2;
reg   [0:0] rev_reg_598;
wire   [0:0] rev32_fu_406_p2;
reg   [0:0] rev32_reg_603;
wire   [7:0] sub_i182_fu_413_p2;
reg   [7:0] sub_i182_reg_608;
wire   [7:0] sub_i_fu_420_p2;
reg   [7:0] sub_i_reg_613;
wire  signed [7:0] add_fu_427_p2;
reg   [7:0] add_reg_618;
wire  signed [24:0] trunc_ln72_1_fu_458_p1;
reg  signed [24:0] trunc_ln72_1_reg_625;
wire    ap_CS_fsm_state6;
wire   [31:0] grp_fu_144_p2;
reg   [31:0] mul_ln71_reg_630;
wire    ap_CS_fsm_state7;
wire  signed [24:0] trunc_ln72_fu_470_p1;
reg  signed [24:0] trunc_ln72_reg_635;
wire    ap_CS_fsm_state8;
wire   [24:0] total_fu_138_p2;
reg   [24:0] total_reg_643;
wire    ap_CS_fsm_state9;
wire   [8:0] add121_fu_481_p2;
reg   [8:0] add121_reg_649;
reg   [7:0] HistArray_address0;
reg    HistArray_ce0;
reg    HistArray_we0;
reg   [32:0] HistArray_d0;
wire   [32:0] HistArray_q0;
reg    grp_Inverse_fu_83_ap_start;
wire    grp_Inverse_fu_83_ap_done;
wire    grp_Inverse_fu_83_ap_idle;
wire    grp_Inverse_fu_83_ap_ready;
reg    grp_Inverse_fu_83_ap_ce;
reg   [15:0] grp_Inverse_fu_83_x;
reg   [4:0] grp_Inverse_fu_83_M;
wire   [31:0] grp_Inverse_fu_83_ap_return_0;
wire   [7:0] grp_Inverse_fu_83_ap_return_1;
reg    grp_Inverse_fu_93_ap_start;
wire    grp_Inverse_fu_93_ap_done;
wire    grp_Inverse_fu_93_ap_idle;
wire    grp_Inverse_fu_93_ap_ready;
wire   [31:0] grp_Inverse_fu_93_ap_return_0;
wire   [7:0] grp_Inverse_fu_93_ap_return_1;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_done;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_idle;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_ready;
wire   [7:0] grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_p_hist_0_address0;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_p_hist_0_ce0;
wire   [7:0] grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_address0;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_ce0;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_we0;
wire   [32:0] grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_d0;
wire   [31:0] grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_din0;
wire   [31:0] grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_din1;
wire    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_ce;
wire    grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start;
wire    grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_done;
wire    grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_idle;
wire    grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_ready;
wire   [7:0] grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_HistArray_address0;
wire    grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_HistArray_ce0;
wire   [31:0] grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_sum_out;
wire    grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_sum_out_ap_vld;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_done;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_idle;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_ready;
wire   [7:0] grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_HistArray_address0;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_HistArray_ce0;
wire   [7:0] grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_max_val_2_out;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_max_val_2_out_ap_vld;
wire   [15:0] grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_din1;
wire  signed [4:0] grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_din2;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_ce;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_start;
wire   [31:0] grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_din0;
wire   [31:0] grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_din1;
wire    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_ce;
reg    grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start_reg;
reg    grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start_reg;
reg    grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start_reg;
wire    ap_CS_fsm_state10;
reg   [7:0] max_val_2_loc_fu_56;
wire    ap_CS_fsm_state11;
wire   [10:0] grp_fu_144_p1;
wire   [7:0] and_ln_fu_189_p3;
wire   [7:0] and_ln1_fu_225_p3;
wire   [6:0] add_ln54_fu_245_p2;
wire   [31:0] zext_ln54_fu_250_p1;
wire   [31:0] zext_ln57_fu_259_p1;
wire   [0:0] xor_ln56_fu_267_p2;
wire   [31:0] wdt_1_fu_254_p2;
wire   [31:0] wdt_2_fu_262_p2;
wire   [0:0] xor_ln53_fu_284_p2;
wire   [0:0] and_ln56_fu_289_p2;
wire   [31:0] wdt_3_fu_277_p3;
wire   [6:0] add_ln61_fu_302_p2;
wire   [31:0] zext_ln61_fu_307_p1;
wire   [31:0] zext_ln64_fu_316_p1;
wire   [0:0] xor_ln63_fu_324_p2;
wire   [31:0] hgt_1_fu_311_p2;
wire   [31:0] hgt_2_fu_319_p2;
wire   [0:0] xor_ln60_fu_341_p2;
wire   [0:0] and_ln63_fu_346_p2;
wire   [31:0] hgt_3_fu_334_p3;
wire   [0:0] or_ln56_fu_272_p2;
wire   [0:0] or_ln63_fu_329_p2;
wire   [0:0] tmp_2_fu_383_p3;
wire   [0:0] tmp_3_fu_398_p3;
wire  signed [7:0] sext_ln71_1_fu_375_p1;
wire  signed [7:0] sext_ln35_fu_379_p1;
wire   [31:0] shl_ln70_fu_436_p2;
wire   [31:0] shl_ln70_1_fu_441_p2;
wire   [31:0] add_ln70_fu_446_p2;
wire  signed [31:0] sext_ln70_fu_433_p1;
wire   [31:0] lshr_ln70_fu_452_p2;
wire  signed [31:0] sext_ln71_fu_462_p1;
wire   [31:0] lshr_ln71_fu_465_p2;
wire  signed [8:0] sext_ln100_fu_478_p1;
reg    grp_fu_144_ce;
wire   [63:0] grp_fu_654_p2;
reg   [31:0] grp_fu_654_p0;
reg   [31:0] grp_fu_654_p1;
reg    grp_fu_654_ce;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start_reg = 1'b0;
#0 grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start_reg = 1'b0;
#0 grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start_reg = 1'b0;
end

Otsu_xfOtsuKernel_HistArray_RAM_AUTO_1R1W #(
    .DataWidth( 33 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
HistArray_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(HistArray_address0),
    .ce0(HistArray_ce0),
    .we0(HistArray_we0),
    .d0(HistArray_d0),
    .q0(HistArray_q0)
);

Otsu_Inverse grp_Inverse_fu_83(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Inverse_fu_83_ap_start),
    .ap_done(grp_Inverse_fu_83_ap_done),
    .ap_idle(grp_Inverse_fu_83_ap_idle),
    .ap_ready(grp_Inverse_fu_83_ap_ready),
    .ap_ce(grp_Inverse_fu_83_ap_ce),
    .x(grp_Inverse_fu_83_x),
    .M(grp_Inverse_fu_83_M),
    .ap_return_0(grp_Inverse_fu_83_ap_return_0),
    .ap_return_1(grp_Inverse_fu_83_ap_return_1)
);

Otsu_Inverse grp_Inverse_fu_93(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Inverse_fu_93_ap_start),
    .ap_done(grp_Inverse_fu_93_ap_done),
    .ap_idle(grp_Inverse_fu_93_ap_idle),
    .ap_ready(grp_Inverse_fu_93_ap_ready),
    .ap_ce(1'b1),
    .x(16'd720),
    .M(5'd16),
    .ap_return_0(grp_Inverse_fu_93_ap_return_0),
    .ap_return_1(grp_Inverse_fu_93_ap_return_1)
);

Otsu_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start),
    .ap_done(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_done),
    .ap_idle(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_idle),
    .ap_ready(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_ready),
    .p_hist_0_address0(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_p_hist_0_address0),
    .p_hist_0_ce0(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_p_hist_0_ce0),
    .p_hist_0_q0(p_hist_0_q0),
    .wdt_1_cast(wdt_4_reg_573),
    .sh_prom_i177_cast_cast_cast_cast(select_ln56_reg_586),
    .sh_prom4_i183_cast_cast_cast_cast(sub_i182_reg_608),
    .cmp_i174(rev_reg_598),
    .conv3_i12_i_i156(hgt_4_reg_580),
    .sh_prom_i_cast_cast_cast_cast(select_ln63_reg_592),
    .sh_prom4_i_cast_cast_cast_cast(sub_i_reg_613),
    .cmp_i(rev32_reg_603),
    .HistArray_address0(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_address0),
    .HistArray_ce0(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_ce0),
    .HistArray_we0(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_we0),
    .HistArray_d0(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_d0),
    .grp_fu_654_p_din0(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_din0),
    .grp_fu_654_p_din1(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_din1),
    .grp_fu_654_p_dout0(grp_fu_654_p2),
    .grp_fu_654_p_ce(grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_ce)
);

Otsu_xfOtsuKernel_Pipeline_SUM_LOOP grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start),
    .ap_done(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_done),
    .ap_idle(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_idle),
    .ap_ready(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_ready),
    .HistArray_address0(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_HistArray_address0),
    .HistArray_ce0(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_HistArray_ce0),
    .HistArray_q0(HistArray_q0),
    .sum_out(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_sum_out),
    .sum_out_ap_vld(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_sum_out_ap_vld)
);

Otsu_xfOtsuKernel_Pipeline_THRESHOLD_LOOP grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start),
    .ap_done(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_done),
    .ap_idle(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_idle),
    .ap_ready(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_ready),
    .HistArray_address0(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_HistArray_address0),
    .HistArray_ce0(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_HistArray_ce0),
    .HistArray_q0(HistArray_q0),
    .total(total_reg_643),
    .zext_ln104(total_reg_643),
    .sh_prom_cast_cast_cast_cast(add_reg_618),
    .conv106(grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_sum_out),
    .sh_prom122_cast_cast_cast_cast(add121_reg_649),
    .sext_ln100(add_reg_618),
    .max_val_2_out(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_max_val_2_out),
    .max_val_2_out_ap_vld(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_max_val_2_out_ap_vld),
    .grp_Inverse_fu_83_p_din1(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_din1),
    .grp_Inverse_fu_83_p_din2(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_din2),
    .grp_Inverse_fu_83_p_dout0_0(grp_Inverse_fu_83_ap_return_0),
    .grp_Inverse_fu_83_p_dout0_1(grp_Inverse_fu_83_ap_return_1),
    .grp_Inverse_fu_83_p_ce(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_ce),
    .grp_Inverse_fu_83_p_start(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_start),
    .grp_Inverse_fu_83_p_ready(grp_Inverse_fu_83_ap_ready),
    .grp_Inverse_fu_83_p_done(grp_Inverse_fu_83_ap_done),
    .grp_Inverse_fu_83_p_idle(grp_Inverse_fu_83_ap_idle),
    .grp_fu_654_p_din0(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_din0),
    .grp_fu_654_p_din1(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_din1),
    .grp_fu_654_p_dout0(grp_fu_654_p2),
    .grp_fu_654_p_ce(grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_ce)
);

Otsu_mul_25s_25s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
mul_25s_25s_25_1_1_U116(
    .din0(trunc_ln72_reg_635),
    .din1(trunc_ln72_1_reg_625),
    .dout(total_fu_138_p2)
);

Otsu_mul_32s_11ns_32_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 32 ))
mul_32s_11ns_32_2_1_U117(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(hgt_4_reg_580),
    .din1(grp_fu_144_p1),
    .ce(grp_fu_144_ce),
    .dout(grp_fu_144_p2)
);

Otsu_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U118(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_654_p0),
    .din1(grp_fu_654_p1),
    .ce(grp_fu_654_ce),
    .dout(grp_fu_654_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start_reg <= 1'b1;
        end else if ((grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_ready == 1'b1)) begin
            grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start_reg <= 1'b1;
        end else if ((grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_ready == 1'b1)) begin
            grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start_reg <= 1'b1;
        end else if ((grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_ready == 1'b1)) begin
            grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add121_reg_649 <= add121_fu_481_p2;
        total_reg_643 <= total_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_reg_618 <= add_fu_427_p2;
        hgt_4_reg_580 <= hgt_4_fu_351_p3;
        rev32_reg_603 <= rev32_fu_406_p2;
        rev_reg_598 <= rev_fu_391_p2;
        select_ln56_reg_586 <= select_ln56_fu_359_p3;
        select_ln63_reg_592 <= select_ln63_fu_367_p3;
        sub_i182_reg_608 <= sub_i182_fu_413_p2;
        sub_i_reg_613 <= sub_i_fu_420_p2;
        wdt_4_reg_573 <= wdt_4_fu_294_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        hgt_reg_515 <= grp_Inverse_fu_93_ap_return_0;
        icmp_ln53_reg_527 <= icmp_ln53_fu_173_p2;
        icmp_ln56_reg_539 <= icmp_ln56_fu_197_p2;
        icmp_ln60_reg_550 <= icmp_ln60_fu_209_p2;
        icmp_ln63_reg_562 <= icmp_ln63_fu_233_p2;
        sub_ln57_reg_545 <= sub_ln57_fu_203_p2;
        sub_ln64_reg_568 <= sub_ln64_fu_239_p2;
        tmp_1_reg_557 <= {{grp_Inverse_fu_93_ap_return_1[7:1]}};
        tmp_reg_534 <= {{grp_Inverse_fu_83_ap_return_1[7:1]}};
        trunc_ln50_reg_510 <= trunc_ln50_fu_157_p1;
        trunc_ln51_reg_522 <= trunc_ln51_fu_169_p1;
        wdt_reg_503 <= grp_Inverse_fu_83_ap_return_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_max_val_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        max_val_2_loc_fu_56 <= grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_max_val_2_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mul_ln71_reg_630 <= grp_fu_144_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        trunc_ln72_1_reg_625 <= trunc_ln72_1_fu_458_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        trunc_ln72_reg_635 <= trunc_ln72_fu_470_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        HistArray_address0 = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        HistArray_address0 = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_HistArray_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        HistArray_address0 = grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_HistArray_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        HistArray_address0 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_address0;
    end else begin
        HistArray_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        HistArray_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        HistArray_ce0 = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_HistArray_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        HistArray_ce0 = grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_HistArray_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        HistArray_ce0 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_ce0;
    end else begin
        HistArray_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        HistArray_d0 = 33'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        HistArray_d0 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_d0;
    end else begin
        HistArray_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        HistArray_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        HistArray_we0 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_HistArray_we0;
    end else begin
        HistArray_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_Inverse_fu_83_M = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_din2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_Inverse_fu_83_M = 5'd16;
    end else begin
        grp_Inverse_fu_83_M = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_Inverse_fu_83_ap_ce = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_ce;
    end else begin
        grp_Inverse_fu_83_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_Inverse_fu_83_ap_start = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_start;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        grp_Inverse_fu_83_ap_start = 1'b1;
    end else begin
        grp_Inverse_fu_83_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_Inverse_fu_83_x = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_Inverse_fu_83_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_Inverse_fu_83_x = 16'd1280;
    end else begin
        grp_Inverse_fu_83_x = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        grp_Inverse_fu_93_ap_start = 1'b1;
    end else begin
        grp_Inverse_fu_93_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((1'b1 == ap_CS_fsm_state6) & (grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_done == 1'b1)))) begin
        grp_fu_144_ce = 1'b1;
    end else begin
        grp_fu_144_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_654_ce = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_654_ce = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_ce;
    end else begin
        grp_fu_654_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_654_p0 = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_654_p0 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_din0;
    end else begin
        grp_fu_654_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_654_p1 = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_grp_fu_654_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_654_p1 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_grp_fu_654_p_din1;
    end else begin
        grp_fu_654_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add121_fu_481_p2 = ($signed(sext_ln100_fu_478_p1) + $signed(9'd10));

assign add_fu_427_p2 = ($signed(sext_ln35_fu_379_p1) + $signed(sext_ln71_1_fu_375_p1));

assign add_ln54_fu_245_p2 = ($signed(trunc_ln50_reg_510) + $signed(7'd104));

assign add_ln61_fu_302_p2 = ($signed(trunc_ln51_reg_522) + $signed(7'd104));

assign add_ln70_fu_446_p2 = (shl_ln70_fu_436_p2 + shl_ln70_1_fu_441_p2);

assign and_ln1_fu_225_p3 = {{tmp_1_fu_215_p4}, {1'd0}};

assign and_ln56_fu_289_p2 = (xor_ln53_fu_284_p2 & icmp_ln56_reg_539);

assign and_ln63_fu_346_p2 = (xor_ln60_fu_341_p2 & icmp_ln63_reg_562);

assign and_ln_fu_189_p3 = {{tmp_fu_179_p4}, {1'd0}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = max_val_2_loc_fu_56;

assign grp_fu_144_p1 = 32'd720;

assign grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_ap_start_reg;

assign grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start = grp_xfOtsuKernel_Pipeline_SUM_LOOP_fu_118_ap_start_reg;

assign grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start = grp_xfOtsuKernel_Pipeline_THRESHOLD_LOOP_fu_124_ap_start_reg;

assign hgt_1_fu_311_p2 = hgt_reg_515 >> zext_ln61_fu_307_p1;

assign hgt_2_fu_319_p2 = hgt_reg_515 << zext_ln64_fu_316_p1;

assign hgt_3_fu_334_p3 = ((icmp_ln60_reg_550[0:0] == 1'b1) ? hgt_1_fu_311_p2 : hgt_2_fu_319_p2);

assign hgt_4_fu_351_p3 = ((and_ln63_fu_346_p2[0:0] == 1'b1) ? hgt_reg_515 : hgt_3_fu_334_p3);

assign icmp_ln53_fu_173_p2 = (($signed(grp_Inverse_fu_83_ap_return_1) > $signed(8'd24)) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_197_p2 = ((and_ln_fu_189_p3 == grp_Inverse_fu_83_ap_return_1) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_209_p2 = (($signed(grp_Inverse_fu_93_ap_return_1) > $signed(8'd24)) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_233_p2 = ((and_ln1_fu_225_p3 == grp_Inverse_fu_93_ap_return_1) ? 1'b1 : 1'b0);

assign lshr_ln70_fu_452_p2 = add_ln70_fu_446_p2 >> sext_ln70_fu_433_p1;

assign lshr_ln71_fu_465_p2 = mul_ln71_reg_630 >> sext_ln71_fu_462_p1;

assign or_ln56_fu_272_p2 = (xor_ln56_fu_267_p2 | icmp_ln53_reg_527);

assign or_ln63_fu_329_p2 = (xor_ln63_fu_324_p2 | icmp_ln60_reg_550);

assign p_hist_0_address0 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_p_hist_0_address0;

assign p_hist_0_ce0 = grp_xfOtsuKernel_Pipeline_HISTOGRAM_NORM_LOOP_fu_103_p_hist_0_ce0;

assign rev32_fu_406_p2 = (tmp_3_fu_398_p3 ^ 1'd1);

assign rev_fu_391_p2 = (tmp_2_fu_383_p3 ^ 1'd1);

assign select_ln56_fu_359_p3 = ((or_ln56_fu_272_p2[0:0] == 1'b1) ? 7'd12 : tmp_reg_534);

assign select_ln63_fu_367_p3 = ((or_ln63_fu_329_p2[0:0] == 1'b1) ? 7'd12 : tmp_1_reg_557);

assign sext_ln100_fu_478_p1 = $signed(add_reg_618);

assign sext_ln35_fu_379_p1 = select_ln63_fu_367_p3;

assign sext_ln70_fu_433_p1 = $signed(select_ln56_reg_586);

assign sext_ln71_1_fu_375_p1 = select_ln56_fu_359_p3;

assign sext_ln71_fu_462_p1 = $signed(select_ln63_reg_592);

assign shl_ln70_1_fu_441_p2 = wdt_4_reg_573 << 32'd8;

assign shl_ln70_fu_436_p2 = wdt_4_reg_573 << 32'd10;

assign sub_i182_fu_413_p2 = ($signed(8'd0) - $signed(sext_ln71_1_fu_375_p1));

assign sub_i_fu_420_p2 = ($signed(8'd0) - $signed(sext_ln35_fu_379_p1));

assign sub_ln57_fu_203_p2 = (8'd24 - grp_Inverse_fu_83_ap_return_1);

assign sub_ln64_fu_239_p2 = (8'd24 - grp_Inverse_fu_93_ap_return_1);

assign tmp_1_fu_215_p4 = {{grp_Inverse_fu_93_ap_return_1[7:1]}};

assign tmp_2_fu_383_p3 = select_ln56_fu_359_p3[32'd6];

assign tmp_3_fu_398_p3 = select_ln63_fu_367_p3[32'd6];

assign tmp_fu_179_p4 = {{grp_Inverse_fu_83_ap_return_1[7:1]}};

assign trunc_ln50_fu_157_p1 = grp_Inverse_fu_83_ap_return_1[6:0];

assign trunc_ln51_fu_169_p1 = grp_Inverse_fu_93_ap_return_1[6:0];

assign trunc_ln72_1_fu_458_p1 = lshr_ln70_fu_452_p2[24:0];

assign trunc_ln72_fu_470_p1 = lshr_ln71_fu_465_p2[24:0];

assign wdt_1_fu_254_p2 = wdt_reg_503 >> zext_ln54_fu_250_p1;

assign wdt_2_fu_262_p2 = wdt_reg_503 << zext_ln57_fu_259_p1;

assign wdt_3_fu_277_p3 = ((icmp_ln53_reg_527[0:0] == 1'b1) ? wdt_1_fu_254_p2 : wdt_2_fu_262_p2);

assign wdt_4_fu_294_p3 = ((and_ln56_fu_289_p2[0:0] == 1'b1) ? wdt_reg_503 : wdt_3_fu_277_p3);

assign xor_ln53_fu_284_p2 = (icmp_ln53_reg_527 ^ 1'd1);

assign xor_ln56_fu_267_p2 = (icmp_ln56_reg_539 ^ 1'd1);

assign xor_ln60_fu_341_p2 = (icmp_ln60_reg_550 ^ 1'd1);

assign xor_ln63_fu_324_p2 = (icmp_ln63_reg_562 ^ 1'd1);

assign zext_ln54_fu_250_p1 = add_ln54_fu_245_p2;

assign zext_ln57_fu_259_p1 = sub_ln57_reg_545;

assign zext_ln61_fu_307_p1 = add_ln61_fu_302_p2;

assign zext_ln64_fu_316_p1 = sub_ln64_reg_568;

endmodule //Otsu_xfOtsuKernel
