-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity QuantizationDithering_xf_QuatizationDithering_16_16_720_1280_64_256_1_2_2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    stream_in_rows_dout : IN STD_LOGIC_VECTOR (9 downto 0);
    stream_in_rows_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_rows_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_rows_empty_n : IN STD_LOGIC;
    stream_in_rows_read : OUT STD_LOGIC;
    stream_in_cols_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    stream_in_cols_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_cols_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    stream_in_cols_empty_n : IN STD_LOGIC;
    stream_in_cols_read : OUT STD_LOGIC;
    img0_data_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img0_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img0_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img0_data_empty_n : IN STD_LOGIC;
    img0_data_read : OUT STD_LOGIC;
    img1_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    img1_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img1_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img1_data_full_n : IN STD_LOGIC;
    img1_data_write : OUT STD_LOGIC );
end;


architecture behav of QuantizationDithering_xf_QuatizationDithering_16_16_720_1280_64_256_1_2_2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal stream_in_rows_blk_n : STD_LOGIC;
    signal stream_in_cols_blk_n : STD_LOGIC;
    signal width_reg_113 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal height_reg_121 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln177_fu_92_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln177_reg_126 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal mul_ln177_fu_106_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal mul_ln177_reg_131 : STD_LOGIC_VECTOR (20 downto 0);
    signal offset_buffer_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal offset_buffer_ce0 : STD_LOGIC;
    signal offset_buffer_we0 : STD_LOGIC;
    signal offset_buffer_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal offset_buffer_ce1 : STD_LOGIC;
    signal offset_buffer_q1 : STD_LOGIC_VECTOR (6 downto 0);
    signal offset_buffer_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal offset_buffer_1_ce0 : STD_LOGIC;
    signal offset_buffer_1_we0 : STD_LOGIC;
    signal offset_buffer_1_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal offset_buffer_1_ce1 : STD_LOGIC;
    signal offset_buffer_1_q1 : STD_LOGIC_VECTOR (6 downto 0);
    signal offset_buffer_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal offset_buffer_2_ce0 : STD_LOGIC;
    signal offset_buffer_2_we0 : STD_LOGIC;
    signal offset_buffer_2_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal offset_buffer_2_ce1 : STD_LOGIC;
    signal offset_buffer_2_q1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_done : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_idle : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_ready : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_ce0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_we0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_ce0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_we0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_ce0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_we0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_idle : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_ready : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img0_data_read : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img1_data_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img1_data_write : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_we0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce1 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_we0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce1 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_we0 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_d0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce1 : STD_LOGIC;
    signal grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal zext_ln109_fu_89_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mul_ln177_fu_106_p0 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln177_fu_106_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal mul_ln177_fu_106_p00 : STD_LOGIC_VECTOR (20 downto 0);
    signal mul_ln177_fu_106_p10 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component QuantizationDithering_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        width : IN STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_2_ce0 : OUT STD_LOGIC;
        offset_buffer_2_we0 : OUT STD_LOGIC;
        offset_buffer_2_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        offset_buffer_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_1_ce0 : OUT STD_LOGIC;
        offset_buffer_1_we0 : OUT STD_LOGIC;
        offset_buffer_1_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        offset_buffer_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_ce0 : OUT STD_LOGIC;
        offset_buffer_we0 : OUT STD_LOGIC;
        offset_buffer_d0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component QuantizationDithering_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img0_data_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img0_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img0_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img0_data_empty_n : IN STD_LOGIC;
        img0_data_read : OUT STD_LOGIC;
        img1_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        img1_data_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img1_data_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img1_data_full_n : IN STD_LOGIC;
        img1_data_write : OUT STD_LOGIC;
        mul_ln177 : IN STD_LOGIC_VECTOR (20 downto 0);
        offset_buffer_2_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_2_ce0 : OUT STD_LOGIC;
        offset_buffer_2_we0 : OUT STD_LOGIC;
        offset_buffer_2_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        offset_buffer_2_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_2_ce1 : OUT STD_LOGIC;
        offset_buffer_2_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
        offset_buffer_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_1_ce0 : OUT STD_LOGIC;
        offset_buffer_1_we0 : OUT STD_LOGIC;
        offset_buffer_1_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        offset_buffer_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_1_ce1 : OUT STD_LOGIC;
        offset_buffer_1_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
        width : IN STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_ce0 : OUT STD_LOGIC;
        offset_buffer_we0 : OUT STD_LOGIC;
        offset_buffer_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        offset_buffer_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        offset_buffer_ce1 : OUT STD_LOGIC;
        offset_buffer_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
        add_ln177 : IN STD_LOGIC_VECTOR (11 downto 0);
        zext_ln109 : IN STD_LOGIC_VECTOR (10 downto 0) );
    end component;


    component QuantizationDithering_mul_10ns_12ns_21_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (9 downto 0);
        din1 : IN STD_LOGIC_VECTOR (11 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component QuantizationDithering_xf_QuatizationDithering_16_16_720_1280_64_256_1_2_2_s_offset_buffer_RAM_AUTO_bkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (6 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    offset_buffer_U : component QuantizationDithering_xf_QuatizationDithering_16_16_720_1280_64_256_1_2_2_s_offset_buffer_RAM_AUTO_bkb
    generic map (
        DataWidth => 7,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => offset_buffer_address0,
        ce0 => offset_buffer_ce0,
        we0 => offset_buffer_we0,
        d0 => offset_buffer_d0,
        address1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_address1,
        ce1 => offset_buffer_ce1,
        q1 => offset_buffer_q1);

    offset_buffer_1_U : component QuantizationDithering_xf_QuatizationDithering_16_16_720_1280_64_256_1_2_2_s_offset_buffer_RAM_AUTO_bkb
    generic map (
        DataWidth => 7,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => offset_buffer_1_address0,
        ce0 => offset_buffer_1_ce0,
        we0 => offset_buffer_1_we0,
        d0 => offset_buffer_1_d0,
        address1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_address1,
        ce1 => offset_buffer_1_ce1,
        q1 => offset_buffer_1_q1);

    offset_buffer_2_U : component QuantizationDithering_xf_QuatizationDithering_16_16_720_1280_64_256_1_2_2_s_offset_buffer_RAM_AUTO_bkb
    generic map (
        DataWidth => 7,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => offset_buffer_2_address0,
        ce0 => offset_buffer_2_ce0,
        we0 => offset_buffer_2_we0,
        d0 => offset_buffer_2_d0,
        address1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_address1,
        ce1 => offset_buffer_2_ce1,
        q1 => offset_buffer_2_q1);

    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66 : component QuantizationDithering_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start,
        ap_done => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_done,
        ap_idle => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_idle,
        ap_ready => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_ready,
        width => width_reg_113,
        offset_buffer_2_address0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_address0,
        offset_buffer_2_ce0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_ce0,
        offset_buffer_2_we0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_we0,
        offset_buffer_2_d0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_d0,
        offset_buffer_1_address0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_address0,
        offset_buffer_1_ce0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_ce0,
        offset_buffer_1_we0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_we0,
        offset_buffer_1_d0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_d0,
        offset_buffer_address0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_address0,
        offset_buffer_ce0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_ce0,
        offset_buffer_we0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_we0,
        offset_buffer_d0 => grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_d0);

    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74 : component QuantizationDithering_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start,
        ap_done => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done,
        ap_idle => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_idle,
        ap_ready => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_ready,
        img0_data_dout => img0_data_dout,
        img0_data_num_data_valid => ap_const_lv2_0,
        img0_data_fifo_cap => ap_const_lv2_0,
        img0_data_empty_n => img0_data_empty_n,
        img0_data_read => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img0_data_read,
        img1_data_din => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img1_data_din,
        img1_data_num_data_valid => ap_const_lv2_0,
        img1_data_fifo_cap => ap_const_lv2_0,
        img1_data_full_n => img1_data_full_n,
        img1_data_write => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img1_data_write,
        mul_ln177 => mul_ln177_reg_131,
        offset_buffer_2_address0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_address0,
        offset_buffer_2_ce0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce0,
        offset_buffer_2_we0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_we0,
        offset_buffer_2_d0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_d0,
        offset_buffer_2_address1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_address1,
        offset_buffer_2_ce1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce1,
        offset_buffer_2_q1 => offset_buffer_2_q1,
        offset_buffer_1_address0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_address0,
        offset_buffer_1_ce0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce0,
        offset_buffer_1_we0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_we0,
        offset_buffer_1_d0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_d0,
        offset_buffer_1_address1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_address1,
        offset_buffer_1_ce1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce1,
        offset_buffer_1_q1 => offset_buffer_1_q1,
        width => width_reg_113,
        offset_buffer_address0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_address0,
        offset_buffer_ce0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce0,
        offset_buffer_we0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_we0,
        offset_buffer_d0 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_d0,
        offset_buffer_address1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_address1,
        offset_buffer_ce1 => grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce1,
        offset_buffer_q1 => offset_buffer_q1,
        add_ln177 => add_ln177_reg_126,
        zext_ln109 => width_reg_113);

    mul_10ns_12ns_21_1_1_U65 : component QuantizationDithering_mul_10ns_12ns_21_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 10,
        din1_WIDTH => 12,
        dout_WIDTH => 21)
    port map (
        din0 => mul_ln177_fu_106_p0,
        din1 => mul_ln177_fu_106_p1,
        dout => mul_ln177_fu_106_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_ready = ap_const_logic_1)) then 
                    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_ready = ap_const_logic_1)) then 
                    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln177_reg_126 <= add_ln177_fu_92_p2;
                mul_ln177_reg_131 <= mul_ln177_fu_106_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((stream_in_cols_empty_n = ap_const_logic_0) or (stream_in_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                height_reg_121 <= stream_in_rows_dout;
                width_reg_113 <= stream_in_cols_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, stream_in_rows_empty_n, stream_in_cols_empty_n, grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_done, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((stream_in_cols_empty_n = ap_const_logic_0) or (stream_in_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln177_fu_92_p2 <= std_logic_vector(unsigned(zext_ln109_fu_89_p1) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg, stream_in_rows_empty_n, stream_in_cols_empty_n)
    begin
        if (((stream_in_cols_empty_n = ap_const_logic_0) or (stream_in_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_done)
    begin
        if ((grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done)
    begin
        if ((grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, stream_in_rows_empty_n, stream_in_cols_empty_n)
    begin
                ap_block_state1 <= ((stream_in_cols_empty_n = ap_const_logic_0) or (stream_in_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_start_reg;
    grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_ap_start_reg;

    img0_data_read_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img0_data_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img0_data_read <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img0_data_read;
        else 
            img0_data_read <= ap_const_logic_0;
        end if; 
    end process;

    img1_data_din <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img1_data_din;

    img1_data_write_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img1_data_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img1_data_write <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_img1_data_write;
        else 
            img1_data_write <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_ap_done = ap_const_logic_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln177_fu_106_p0 <= mul_ln177_fu_106_p00(10 - 1 downto 0);
    mul_ln177_fu_106_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_reg_121),21));
    mul_ln177_fu_106_p1 <= mul_ln177_fu_106_p10(12 - 1 downto 0);
    mul_ln177_fu_106_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln177_fu_92_p2),21));

    offset_buffer_1_address0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_address0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_1_address0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_1_address0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_address0;
        else 
            offset_buffer_1_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    offset_buffer_1_ce0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_ce0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_1_ce0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_1_ce0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_ce0;
        else 
            offset_buffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_1_ce1_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_1_ce1 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_ce1;
        else 
            offset_buffer_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_1_d0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_d0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_d0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_1_d0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_1_d0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_d0;
        else 
            offset_buffer_1_d0 <= "XXXXXXX";
        end if; 
    end process;


    offset_buffer_1_we0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_we0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_we0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_1_we0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_1_we0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_1_we0;
        else 
            offset_buffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_2_address0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_address0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_2_address0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_2_address0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_address0;
        else 
            offset_buffer_2_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    offset_buffer_2_ce0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_ce0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_2_ce0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_2_ce0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_ce0;
        else 
            offset_buffer_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_2_ce1_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_2_ce1 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_ce1;
        else 
            offset_buffer_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_2_d0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_d0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_d0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_2_d0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_2_d0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_d0;
        else 
            offset_buffer_2_d0 <= "XXXXXXX";
        end if; 
    end process;


    offset_buffer_2_we0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_we0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_we0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_2_we0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_2_we0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_2_we0;
        else 
            offset_buffer_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_address0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_address0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_address0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_address0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_address0;
        else 
            offset_buffer_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    offset_buffer_ce0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_ce0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_ce0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_ce0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_ce0;
        else 
            offset_buffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_ce1_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_ce1 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_ce1;
        else 
            offset_buffer_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    offset_buffer_d0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_d0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_d0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_d0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_d0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_d0;
        else 
            offset_buffer_d0 <= "XXXXXXX";
        end if; 
    end process;


    offset_buffer_we0_assign_proc : process(grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_we0, grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_we0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            offset_buffer_we0 <= grp_xf_QuatizationDithering_Pipeline_LOOP_ROW_LOOP_COL_fu_74_offset_buffer_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            offset_buffer_we0 <= grp_xf_QuatizationDithering_Pipeline_VITIS_LOOP_122_1_fu_66_offset_buffer_we0;
        else 
            offset_buffer_we0 <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_cols_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, stream_in_cols_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            stream_in_cols_blk_n <= stream_in_cols_empty_n;
        else 
            stream_in_cols_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_cols_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, stream_in_rows_empty_n, stream_in_cols_empty_n)
    begin
        if ((not(((stream_in_cols_empty_n = ap_const_logic_0) or (stream_in_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            stream_in_cols_read <= ap_const_logic_1;
        else 
            stream_in_cols_read <= ap_const_logic_0;
        end if; 
    end process;


    stream_in_rows_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, stream_in_rows_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            stream_in_rows_blk_n <= stream_in_rows_empty_n;
        else 
            stream_in_rows_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    stream_in_rows_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, stream_in_rows_empty_n, stream_in_cols_empty_n)
    begin
        if ((not(((stream_in_cols_empty_n = ap_const_logic_0) or (stream_in_rows_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            stream_in_rows_read <= ap_const_logic_1;
        else 
            stream_in_rows_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln109_fu_89_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_reg_113),12));
end behav;
