// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img0_data_dout,
        img0_data_num_data_valid,
        img0_data_fifo_cap,
        img0_data_empty_n,
        img0_data_read,
        img1_data_din,
        img1_data_num_data_valid,
        img1_data_fifo_cap,
        img1_data_full_n,
        img1_data_write,
        img_height,
        img_width
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] img0_data_dout;
input  [1:0] img0_data_num_data_valid;
input  [1:0] img0_data_fifo_cap;
input   img0_data_empty_n;
output   img0_data_read;
output  [23:0] img1_data_din;
input  [1:0] img1_data_num_data_valid;
input  [1:0] img1_data_fifo_cap;
input   img1_data_full_n;
output   img1_data_write;
input  [9:0] img_height;
input  [10:0] img_width;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img0_data_read;
reg img1_data_write;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state3;
wire   [1:0] trunc_ln415_fu_187_p1;
reg   [1:0] trunc_ln415_reg_445;
wire   [11:0] zext_ln415_2_fu_195_p1;
reg   [11:0] zext_ln415_2_reg_450;
wire   [63:0] zext_ln415_1_fu_199_p1;
reg   [63:0] zext_ln415_1_reg_455;
wire   [1:0] trunc_ln415_1_fu_216_p1;
reg   [1:0] trunc_ln415_1_reg_463;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln415_fu_211_p2;
wire   [10:0] img_height_cast_fu_249_p1;
reg   [10:0] img_height_cast_reg_496;
wire    ap_CS_fsm_state6;
wire  signed [11:0] sext_ln446_fu_258_p1;
reg  signed [11:0] sext_ln446_reg_501;
wire   [11:0] add_ln446_fu_262_p2;
reg   [11:0] add_ln446_reg_507;
wire   [10:0] add_ln446_1_fu_267_p2;
reg   [10:0] add_ln446_1_reg_512;
wire   [1:0] trunc_ln446_fu_285_p1;
reg   [1:0] trunc_ln446_reg_517;
wire    ap_CS_fsm_state7;
wire   [1:0] trunc_ln446_1_fu_289_p1;
reg   [1:0] trunc_ln446_1_reg_522;
wire   [1:0] trunc_ln446_2_fu_293_p1;
reg   [1:0] trunc_ln446_2_reg_527;
wire   [0:0] cmp_i_i321_i_fu_306_p2;
reg   [0:0] cmp_i_i321_i_reg_535;
wire   [0:0] icmp_ln446_fu_301_p2;
wire   [1:0] empty_28_fu_331_p1;
reg   [1:0] empty_28_reg_540;
wire   [0:0] spec_select47_fu_343_p2;
reg   [0:0] spec_select47_reg_545;
wire   [0:0] spec_select51_fu_355_p2;
reg   [0:0] spec_select51_reg_550;
wire   [0:0] spec_select55_fu_367_p2;
reg   [0:0] spec_select55_reg_555;
reg   [10:0] buf_address0;
reg    buf_ce0;
wire   [23:0] buf_q0;
reg   [10:0] buf_address1;
reg    buf_ce1;
reg    buf_we1;
reg   [23:0] buf_d1;
reg   [10:0] buf_1_address0;
reg    buf_1_ce0;
wire   [23:0] buf_1_q0;
reg   [10:0] buf_1_address1;
reg    buf_1_ce1;
reg    buf_1_we1;
reg   [23:0] buf_1_d1;
reg   [10:0] buf_2_address0;
reg    buf_2_ce0;
wire   [23:0] buf_2_q0;
reg   [10:0] buf_2_address1;
reg    buf_2_ce1;
reg    buf_2_we1;
reg   [23:0] buf_2_d1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_done;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_idle;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_ready;
wire   [12:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_5_out;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_5_out_ap_vld;
wire   [12:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_4_out;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_4_out_ap_vld;
wire   [12:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_3_out;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_3_out_ap_vld;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_done;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_idle;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_ready;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_img0_data_read;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_address1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_ce1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_we1;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_d1;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_address1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_ce1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_we1;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_d1;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_address1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_ce1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_we1;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_d1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_done;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_idle;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_ready;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_address0;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_ce0;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_address1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_ce1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_we1;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_d1;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_1_address0;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_1_ce0;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_2_address0;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_2_ce0;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_done;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_idle;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_ready;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img0_data_read;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img1_data_din;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img1_data_write;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_address0;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_ce0;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_address1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_ce1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_we1;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_d1;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_address0;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_ce0;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_address1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_ce1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_we1;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_d1;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_address0;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_ce0;
wire   [10:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_address1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_ce1;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_we1;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_d1;
reg    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start_reg;
reg    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [63:0] init_buf_fu_74;
wire   [63:0] add_ln415_fu_221_p2;
wire   [63:0] zext_ln415_fu_191_p1;
reg   [10:0] row_fu_102;
wire   [10:0] row_3_fu_373_p2;
reg   [12:0] row_ind_fu_106;
reg   [12:0] row_ind_6_fu_110;
reg   [12:0] row_ind_7_fu_114;
wire   [10:0] sub336_i_fu_252_p2;
wire   [11:0] zext_ln446_fu_297_p1;
wire   [11:0] sub_i_i237_i_fu_316_p2;
wire   [10:0] empty_27_fu_321_p1;
wire   [10:0] sub_i213_i_cast17_fu_325_p2;
wire   [0:0] cmp_i_i269_i_fu_311_p2;
wire   [0:0] tmp_fu_335_p3;
wire   [0:0] cmp_i_i193_i_1_fu_349_p2;
wire   [0:0] cmp_i_i193_i_2_fu_361_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start_reg = 1'b0;
#0 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start_reg = 1'b0;
#0 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start_reg = 1'b0;
#0 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start_reg = 1'b0;
end

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_address0),
    .ce0(buf_ce0),
    .q0(buf_q0),
    .address1(buf_address1),
    .ce1(buf_ce1),
    .we1(buf_we1),
    .d1(buf_d1)
);

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_1_address0),
    .ce0(buf_1_ce0),
    .q0(buf_1_q0),
    .address1(buf_1_address1),
    .ce1(buf_1_ce1),
    .we1(buf_1_we1),
    .d1(buf_1_d1)
);

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_buf_RAM_S2P_BRAM_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
buf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2_address0),
    .ce0(buf_2_ce0),
    .q0(buf_2_q0),
    .address1(buf_2_address1),
    .ce1(buf_2_ce1),
    .we1(buf_2_we1),
    .d1(buf_2_d1)
);

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start),
    .ap_done(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_done),
    .ap_idle(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_idle),
    .ap_ready(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_ready),
    .row_ind_5_out(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_5_out),
    .row_ind_5_out_ap_vld(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_5_out_ap_vld),
    .row_ind_4_out(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_4_out),
    .row_ind_4_out_ap_vld(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_4_out_ap_vld),
    .row_ind_3_out(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_3_out),
    .row_ind_3_out_ap_vld(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_3_out_ap_vld)
);

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start),
    .ap_done(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_done),
    .ap_idle(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_idle),
    .ap_ready(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_ready),
    .img0_data_dout(img0_data_dout),
    .img0_data_num_data_valid(2'd0),
    .img0_data_fifo_cap(2'd0),
    .img0_data_empty_n(img0_data_empty_n),
    .img0_data_read(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_img0_data_read),
    .img_width(img_width),
    .buf_2_address1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_address1),
    .buf_2_ce1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_ce1),
    .buf_2_we1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_we1),
    .buf_2_d1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_d1),
    .buf_1_address1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_address1),
    .buf_1_ce1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_ce1),
    .buf_1_we1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_we1),
    .buf_1_d1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_d1),
    .buf_r_address1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_address1),
    .buf_r_ce1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_ce1),
    .buf_r_we1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_we1),
    .buf_r_d1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_d1),
    .trunc_ln415_1(trunc_ln415_1_reg_463)
);

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start),
    .ap_done(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_done),
    .ap_idle(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_idle),
    .ap_ready(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_ready),
    .img_width(img_width),
    .buf_r_address0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_address0),
    .buf_r_ce0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_ce0),
    .buf_r_q0(buf_q0),
    .buf_r_address1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_address1),
    .buf_r_ce1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_ce1),
    .buf_r_we1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_we1),
    .buf_r_d1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_d1),
    .buf_1_address0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_1_address0),
    .buf_1_ce0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_1_ce0),
    .buf_1_q0(buf_1_q0),
    .buf_2_address0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_2_address0),
    .buf_2_ce0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_2_ce0),
    .buf_2_q0(buf_2_q0),
    .trunc_ln1(trunc_ln415_reg_445)
);

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start),
    .ap_done(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_done),
    .ap_idle(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_idle),
    .ap_ready(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_ready),
    .img0_data_dout(img0_data_dout),
    .img0_data_num_data_valid(2'd0),
    .img0_data_fifo_cap(2'd0),
    .img0_data_empty_n(img0_data_empty_n),
    .img0_data_read(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img0_data_read),
    .img1_data_din(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img1_data_din),
    .img1_data_num_data_valid(2'd0),
    .img1_data_fifo_cap(2'd0),
    .img1_data_full_n(img1_data_full_n),
    .img1_data_write(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img1_data_write),
    .add_ln446(add_ln446_reg_507),
    .buf_2_address0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_address0),
    .buf_2_ce0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_ce0),
    .buf_2_q0(buf_2_q0),
    .buf_2_address1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_address1),
    .buf_2_ce1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_ce1),
    .buf_2_we1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_we1),
    .buf_2_d1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_d1),
    .buf_r_address0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_address0),
    .buf_r_ce0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_ce0),
    .buf_r_q0(buf_q0),
    .buf_r_address1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_address1),
    .buf_r_ce1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_ce1),
    .buf_r_we1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_we1),
    .buf_r_d1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_d1),
    .buf_1_address0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_address0),
    .buf_1_ce0(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_ce0),
    .buf_1_q0(buf_1_q0),
    .buf_1_address1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_address1),
    .buf_1_ce1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_ce1),
    .buf_1_we1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_we1),
    .buf_1_d1(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_d1),
    .row_ind_9(trunc_ln446_2_reg_527),
    .row_ind_8(trunc_ln446_1_reg_522),
    .row_ind_7(trunc_ln446_reg_517),
    .sub_i213_i_cast(empty_28_reg_540),
    .spec_select47(spec_select47_reg_545),
    .spec_select51(spec_select51_reg_550),
    .spec_select55(spec_select55_reg_555),
    .zext_ln415_2(img_width),
    .cmp_i_i321_i(cmp_i_i321_i_reg_535)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_ready == 1'b1)) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_ready == 1'b1)) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln415_fu_211_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start_reg <= 1'b1;
        end else if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_ready == 1'b1)) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln415_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_ready == 1'b1)) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        init_buf_fu_74 <= zext_ln415_fu_191_p1;
    end else if (((icmp_ln415_fu_211_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        init_buf_fu_74 <= add_ln415_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln415_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        row_fu_102 <= 11'd1;
    end else if (((icmp_ln446_fu_301_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        row_fu_102 <= row_3_fu_373_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln415_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        row_ind_6_fu_110 <= grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_4_out;
    end else if (((icmp_ln446_fu_301_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        row_ind_6_fu_110 <= row_ind_7_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln415_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        row_ind_7_fu_114 <= grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_5_out;
    end else if (((icmp_ln446_fu_301_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        row_ind_7_fu_114 <= row_ind_fu_106;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln415_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        row_ind_fu_106 <= grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_3_out;
    end else if (((icmp_ln446_fu_301_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        row_ind_fu_106 <= row_ind_6_fu_110;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        add_ln446_1_reg_512 <= add_ln446_1_fu_267_p2;
        add_ln446_reg_507 <= add_ln446_fu_262_p2;
        img_height_cast_reg_496[9 : 0] <= img_height_cast_fu_249_p1[9 : 0];
        sext_ln446_reg_501 <= sext_ln446_fu_258_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln446_fu_301_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        cmp_i_i321_i_reg_535 <= cmp_i_i321_i_fu_306_p2;
        empty_28_reg_540 <= empty_28_fu_331_p1;
        spec_select47_reg_545 <= spec_select47_fu_343_p2;
        spec_select51_reg_550 <= spec_select51_fu_355_p2;
        spec_select55_reg_555 <= spec_select55_fu_367_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln415_fu_211_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        trunc_ln415_1_reg_463 <= trunc_ln415_1_fu_216_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        trunc_ln415_reg_445 <= trunc_ln415_fu_187_p1;
        zext_ln415_1_reg_455[12 : 0] <= zext_ln415_1_fu_199_p1[12 : 0];
        zext_ln415_2_reg_450[10 : 0] <= zext_ln415_2_fu_195_p1[10 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        trunc_ln446_1_reg_522 <= trunc_ln446_1_fu_289_p1;
        trunc_ln446_2_reg_527 <= trunc_ln446_2_fu_293_p1;
        trunc_ln446_reg_517 <= trunc_ln446_fu_285_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln446_fu_301_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln446_fu_301_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_1_address0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_1_address0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_1_address0;
    end else begin
        buf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_1_address1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_address1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_address1;
    end else begin
        buf_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_1_ce0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_1_ce0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_1_ce0;
    end else begin
        buf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_1_ce1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_ce1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_ce1;
    end else begin
        buf_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_1_d1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_d1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_d1;
    end else begin
        buf_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_1_we1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_1_we1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_1_we1;
    end else begin
        buf_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_2_address0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_2_address0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_2_address0;
    end else begin
        buf_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_2_address1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_address1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_address1;
    end else begin
        buf_2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_2_ce0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_2_ce0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_2_ce0;
    end else begin
        buf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_2_ce1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_ce1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_ce1;
    end else begin
        buf_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_2_d1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_d1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_d1;
    end else begin
        buf_2_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_2_we1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_2_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2_we1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_2_we1;
    end else begin
        buf_2_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_address0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_address0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_address0;
    end else begin
        buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_address1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_address1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_address1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_address1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_address1;
    end else begin
        buf_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_ce0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_ce0 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_ce0;
    end else begin
        buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_ce1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_ce1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_ce1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_ce1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_ce1;
    end else begin
        buf_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_d1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_d1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_d1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_d1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_d1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_d1;
    end else begin
        buf_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        buf_we1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_buf_r_we1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_we1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_buf_r_we1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_we1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_buf_r_we1;
    end else begin
        buf_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        img0_data_read = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img0_data_read;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        img0_data_read = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_img0_data_read;
    end else begin
        img0_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        img1_data_write = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img1_data_write;
    end else begin
        img1_data_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln415_fu_211_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln446_fu_301_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln415_fu_221_p2 = (init_buf_fu_74 + 64'd1);

assign add_ln446_1_fu_267_p2 = (img_height_cast_fu_249_p1 + 11'd1);

assign add_ln446_fu_262_p2 = (zext_ln415_2_reg_450 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign cmp_i_i193_i_1_fu_349_p2 = (($signed(sub_i213_i_cast17_fu_325_p2) < $signed(11'd1)) ? 1'b1 : 1'b0);

assign cmp_i_i193_i_2_fu_361_p2 = (($signed(sub_i_i237_i_fu_316_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign cmp_i_i269_i_fu_311_p2 = (($signed(sext_ln446_reg_501) < $signed(zext_ln446_fu_297_p1)) ? 1'b1 : 1'b0);

assign cmp_i_i321_i_fu_306_p2 = ((row_fu_102 < img_height_cast_reg_496) ? 1'b1 : 1'b0);

assign empty_27_fu_321_p1 = sub_i_i237_i_fu_316_p2[10:0];

assign empty_28_fu_331_p1 = sub_i213_i_cast17_fu_325_p2[1:0];

assign grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_ap_start_reg;

assign grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_ap_start_reg;

assign grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_419_2_fu_137_ap_start_reg;

assign grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_431_3_fu_148_ap_start_reg;

assign icmp_ln415_fu_211_p2 = ((init_buf_fu_74 < zext_ln415_1_reg_455) ? 1'b1 : 1'b0);

assign icmp_ln446_fu_301_p2 = ((row_fu_102 == add_ln446_1_reg_512) ? 1'b1 : 1'b0);

assign img1_data_din = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_Col_Loop_fu_157_img1_data_din;

assign img_height_cast_fu_249_p1 = img_height;

assign row_3_fu_373_p2 = (row_fu_102 + 11'd1);

assign sext_ln446_fu_258_p1 = $signed(sub336_i_fu_252_p2);

assign spec_select47_fu_343_p2 = (tmp_fu_335_p3 & cmp_i_i269_i_fu_311_p2);

assign spec_select51_fu_355_p2 = (cmp_i_i269_i_fu_311_p2 & cmp_i_i193_i_1_fu_349_p2);

assign spec_select55_fu_367_p2 = (cmp_i_i269_i_fu_311_p2 & cmp_i_i193_i_2_fu_361_p2);

assign sub336_i_fu_252_p2 = ($signed(img_height_cast_fu_249_p1) + $signed(11'd2047));

assign sub_i213_i_cast17_fu_325_p2 = (11'd2 - empty_27_fu_321_p1);

assign sub_i_i237_i_fu_316_p2 = ($signed(zext_ln446_fu_297_p1) - $signed(sext_ln446_reg_501));

assign tmp_fu_335_p3 = sub_i213_i_cast17_fu_325_p2[32'd10];

assign trunc_ln415_1_fu_216_p1 = init_buf_fu_74[1:0];

assign trunc_ln415_fu_187_p1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_4_out[1:0];

assign trunc_ln446_1_fu_289_p1 = row_ind_6_fu_110[1:0];

assign trunc_ln446_2_fu_293_p1 = row_ind_7_fu_114[1:0];

assign trunc_ln446_fu_285_p1 = row_ind_fu_106[1:0];

assign zext_ln415_1_fu_199_p1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_5_out;

assign zext_ln415_2_fu_195_p1 = img_width;

assign zext_ln415_fu_191_p1 = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_Pipeline_VITIS_LOOP_406_1_fu_130_row_ind_4_out;

assign zext_ln446_fu_297_p1 = row_fu_102;

always @ (posedge ap_clk) begin
    zext_ln415_2_reg_450[11] <= 1'b0;
    zext_ln415_1_reg_455[63:13] <= 51'b000000000000000000000000000000000000000000000000000;
    img_height_cast_reg_496[10] <= 1'b0;
end

endmodule //ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s
