// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ModeFilter_modefilter_3_1_16_720_1280_1_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        p_src_rows_dout,
        p_src_rows_num_data_valid,
        p_src_rows_fifo_cap,
        p_src_rows_empty_n,
        p_src_rows_read,
        p_src_cols_dout,
        p_src_cols_num_data_valid,
        p_src_cols_fifo_cap,
        p_src_cols_empty_n,
        p_src_cols_read,
        img0_data_dout,
        img0_data_num_data_valid,
        img0_data_fifo_cap,
        img0_data_empty_n,
        img0_data_read,
        img1_data_din,
        img1_data_num_data_valid,
        img1_data_fifo_cap,
        img1_data_full_n,
        img1_data_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [9:0] p_src_rows_dout;
input  [1:0] p_src_rows_num_data_valid;
input  [1:0] p_src_rows_fifo_cap;
input   p_src_rows_empty_n;
output   p_src_rows_read;
input  [10:0] p_src_cols_dout;
input  [1:0] p_src_cols_num_data_valid;
input  [1:0] p_src_cols_fifo_cap;
input   p_src_cols_empty_n;
output   p_src_cols_read;
input  [23:0] img0_data_dout;
input  [1:0] img0_data_num_data_valid;
input  [1:0] img0_data_fifo_cap;
input   img0_data_empty_n;
output   img0_data_read;
output  [23:0] img1_data_din;
input  [1:0] img1_data_num_data_valid;
input  [1:0] img1_data_fifo_cap;
input   img1_data_full_n;
output   img1_data_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg p_src_rows_read;
reg p_src_cols_read;
reg img0_data_read;
reg img1_data_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    p_src_rows_blk_n;
reg    p_src_cols_blk_n;
reg   [10:0] imgwidth_reg_58;
reg    ap_block_state1;
reg   [9:0] imgheight_reg_63;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_done;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_idle;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_ready;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img0_data_read;
wire   [23:0] grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img1_data_din;
wire    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img1_data_write;
reg    grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start_reg;
reg    ap_block_state1_ignore_call6;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start_reg = 1'b0;
end

ModeFilter_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start),
    .ap_done(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_done),
    .ap_idle(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_idle),
    .ap_ready(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_ready),
    .img0_data_dout(img0_data_dout),
    .img0_data_num_data_valid(2'd0),
    .img0_data_fifo_cap(2'd0),
    .img0_data_empty_n(img0_data_empty_n),
    .img0_data_read(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img0_data_read),
    .img1_data_din(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img1_data_din),
    .img1_data_num_data_valid(2'd0),
    .img1_data_fifo_cap(2'd0),
    .img1_data_full_n(img1_data_full_n),
    .img1_data_write(grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img1_data_write),
    .img_height(imgheight_reg_63),
    .img_width(imgwidth_reg_58)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start_reg <= 1'b0;
    end else begin
        if ((~((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start_reg <= 1'b1;
        end else if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_ready == 1'b1)) begin
            grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        imgheight_reg_63 <= p_src_rows_dout;
        imgwidth_reg_58 <= p_src_cols_dout;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img0_data_read = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img0_data_read;
    end else begin
        img0_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        img1_data_write = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img1_data_write;
    end else begin
        img1_data_write = 1'b0;
    end
end

always @ (*) begin
    if (((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_blk_n = p_src_cols_empty_n;
    end else begin
        p_src_cols_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_cols_read = 1'b1;
    end else begin
        p_src_cols_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_blk_n = p_src_rows_empty_n;
    end else begin
        p_src_rows_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_rows_read = 1'b1;
    end else begin
        p_src_rows_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call6 = ((real_start == 1'b0) | (p_src_cols_empty_n == 1'b0) | (p_src_rows_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_ap_start_reg;

assign img1_data_din = grp_xFModeNxN_720_1280_3_16_1_2_2_0_1281_3_9_s_fu_46_img1_data_din;

assign start_out = real_start;

endmodule //ModeFilter_modefilter_3_1_16_720_1280_1_2_2_s
